import assert from 'node:assert/strict';
import {validateAgentPatch,needsAgentReview,agentInstructions,callAgentModel} from '../functions/_shared/agent.ts';
assert.throws(()=>validateAgentPatch('task',{user_id:'foreign'}));
assert.throws(()=>validateAgentPatch('task',{at:'2026-10-07T12:00:00Z'}));
assert.throws(()=>validateAgentPatch('task',{due_date:'2026-02-30'}));
assert.throws(()=>validateAgentPatch('task',{duration_minutes:7}));
assert.throws(()=>validateAgentPatch('task',{label_ids:['not-an-id']}));
assert.throws(()=>validateAgentPatch('label',{archived:'false'}));
assert.throws(()=>validateAgentPatch('label',{name:''},true));
assert.deepEqual(validateAgentPatch('task',{title:'Comprar leite',label_ids:['new:mercado'],due_date:null},true),{title:'Comprar leite',label_ids:['new:mercado'],due_date:null});
assert.equal(needsAgentReview([{patch:{archived:true}},{patch:{archived_at:'date'}}]),true);
assert.equal(needsAgentReview([{patch:{status:'completed'}}]),false);
assert.match(agentInstructions('analyze','2026-10-06'),/nenhuma alteração é permitida/);
let sent;
const fake=async(_url,options)=>{sent=JSON.parse(options.body);return new Response(JSON.stringify({model:'test/model:free',choices:[{message:{role:'assistant',content:'Há uma tarefa atrasada.'}}]}));};
await callAgentModel([],'analyze','test',fake);
assert.equal(sent.model,'openrouter/free');
assert.equal(sent.tools.some(t=>t.function.name==='propose_changes'),false);
await callAgentModel([],'execute','test',fake);
assert.equal(sent.tools.some(t=>t.function.name==='propose_changes'),true);
await assert.rejects(()=>callAgentModel([],'execute','test',async()=>new Response(JSON.stringify({model:'paid/model',choices:[{message:{content:'ok'}}]}))),/gratuitos/);
await assert.rejects(()=>callAgentModel([],'execute','test',async()=>new Response('{}',{status:429})),/Limite/);
console.log('PASS: agent validation, read-only tools, free-only routing and capacity errors');
