import {capturePipeline,directPerson,chosenPerson} from '../functions/_shared/capturePipeline.ts';
import {captureProfile,defaultCaptureProfile} from '../functions/_shared/captureProfiles.ts';
const assert=(v:unknown,message='Assertion failed')=>{if(!v)throw new Error(message);};
const people=[{id:'ana',name:'Ana Costa'},{id:'other',name:'Ana Lima'}];
const text='Enviei proposta e aguardo Ana Costa, acompanhar sexta; entregar até 12/10/2026';
const task={title:'Aguardar proposta',description:text,sourceText:text,dueDate:'2026-10-12',dueEvidence:'até 12/10/2026',waitingFor:'Ana Costa',followUpDate:'2026-10-09',dateEvidence:'acompanhar sexta',people:[{name:'Ana Costa',role:'waiting_for'}],dateReview:[]};
function mock(profile:'free'|'luna'|'gemini',change:(body:any,result:any)=>any=(_b,r)=>r){const calls:any[]=[];const fetcher=(async(url:any,options:any)=>{const body=JSON.parse(options.body);calls.push({url,body});let output:any;
 if(String(url).endsWith('chat/completions')){if(body.messages[0].content.includes('Classifique o state')){const input=JSON.parse(body.messages[1].content);output={answers:Object.fromEntries(Object.entries(input.questions).map(([name,q]:any)=>[name,q.type==='choice'?{type:'choice',choice:'professional',probabilities:{personal:.01,professional:.99}}:{type:'noul',noul:.99}]))};}else output={tasks:[structuredClone(task)]};return Response.json({model:body.model==='openrouter/free'?'test/model:free':body.model,usage:{cost:profile==='free'?0:.0002,prompt_tokens:100,completion_tokens:20},choices:[{finish_reason:'stop',message:{content:JSON.stringify(change(body,output))}}]});}
 output={model:body.model,usage:{cost:profile==='free'?0:.0001,input_tokens:100,output_tokens:0},answers:Object.fromEntries(Object.entries(body.questions).map(([name,q]:any)=>[name,q.type==='choice'?{type:'choice',choice:'professional',probabilities:{personal:.01,professional:.99}}:{type:'noul',noul:.99}]))};return Response.json(change(body,output));}) as typeof fetch;return {calls,fetcher};}
for(const profile of ['free','luna','gemini'] as const)Deno.test(`capture profile ${profile} uses its own models and preserves dates/people`,async()=>{const {calls,fetcher}=mock(profile);const r=await capturePipeline({text,labels:[]},'synthetic','free',profile,'2026-10-08',people,fetcher);assert(r.results[0].dueDate==='2026-10-12');assert(r.results[0].followUpDate==='2026-10-09');assert(r.results[0].people[0].personId==='ana');assert(r.audit.steps.length===2);assert(Math.abs((r.audit.cost??-1)-(profile==='free'?0:profile==='luna'?.0003:.0004))<1e-10);assert(calls[0].body.model===(profile==='luna'?'openai/gpt-6-luna':profile==='free'?'openrouter/free':'google/gemini-2.5-flash'));assert(!JSON.stringify(calls).includes('attachment'));if(profile==='luna'){assert(calls[1].url.endsWith('alpha/decisions'));assert(calls[1].body.model==='openai/gpt-6-luna-decisions');}});
Deno.test('unknown people remain free names and ambiguous names are not linked',()=>{assert(directPerson('Ana',people)===null);assert(directPerson('ANA CÓSTA',people)==='ana');assert(chosenPerson({type:'choice',choice:'ana',probabilities:{ana:.55,other:.44,none:.01}},people)===null);assert(chosenPerson({type:'choice',choice:'ana',probabilities:{ana:.96,other:.02,none:.02}},people)==='ana');});
Deno.test('missing followup is visibly suggested tomorrow, no due date invented',async()=>{const {fetcher}=mock('luna',(_b,r)=>r.tasks?{tasks:[{...task,dueDate:null,dueEvidence:null,followUpDate:null,dateEvidence:null,people:[{name:'Ana Costa',role:'waiting_for'}]}]}:r);const r=await capturePipeline({text,labels:[]},'synthetic','free','luna','2026-12-31',[],fetcher);assert(r.results[0].followUpDate==='2027-01-01');assert(r.results[0].description.includes('sugerido automaticamente'));assert(r.results[0].dueDate===undefined);assert(r.results[0].people[0].personId===null);});
Deno.test('rejects invented names, invalid dates, wrong served model and refusals without fallback',async()=>{for(const change of [(_b:any,r:any)=>r.tasks?{tasks:[{...task,people:[{name:'Pedro',role:'involved'}]}]}:r,(_b:any,r:any)=>r.tasks?{tasks:[{...task,followUpDate:'2026-02-30'}]}:r,(_b:any,r:any)=>r.answers?{...r,model:'another/model'}:r,(_b:any,r:any)=>r.answers?{...r,answers:{task_0_area:{type:'refusal'}}}:r]){const {fetcher}=mock('luna',change);let rejected=false;try{await capturePipeline({text,labels:[]},'synthetic','free','luna','2026-10-08',people,fetcher);}catch{rejected=true;}assert(rejected);}});
Deno.test('splits classification into at most 200 questions',async()=>{const labels=Array.from({length:201},(_,i)=>({id:`label${i}`,name:`label${i}`,description:'test'}));const {calls,fetcher}=mock('luna');const r=await capturePipeline({text,labels},'synthetic','free','luna','2026-10-08',people,fetcher);assert(r.results[0].labelIds.length===201);assert(calls.length===3);assert(calls.filter(c=>c.body.questions).every(c=>Object.keys(c.body.questions).length<=200));});
Deno.test('profile allowlist and legacy default',()=>{assert(defaultCaptureProfile({default_model:'google/gemini-2.5-flash'})==='gemini');assert(defaultCaptureProfile({capture_profile:'luna',default_model:'openrouter/free'})==='luna');let refused=false;try{captureProfile('random');}catch{refused=true;}assert(refused);});

