import { PGlite } from '../.db-validation/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const a = '00000000-0000-0000-0000-000000000001', b = '00000000-0000-0000-0000-000000000002';
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public to authenticated,anon,service_role;
grant execute on function auth.uid() to authenticated,anon,service_role;
insert into auth.users values ('${a}'),('${b}');`);
await db.exec(await readFile(new URL('./migrations/202610040001_torre.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated; set request.jwt.claim.sub='${a}';`);
const task = (await db.query("insert into torre_tasks(title,area) values ('Teste','professional') returning id")).rows[0].id;
async function rejected(sql) { await assert.rejects(db.exec(sql)); }
await rejected(`insert into torre_tasks(user_id,title,area) values ('${b}','Invasão','personal')`);
await rejected(`update torre_tasks set status='waiting' where id='${task}'`);
await db.exec("insert into torre_work_hours(weekday,enabled) select generate_series(0,6),true");
await db.exec(`insert into torre_scheduled_blocks(task_id,start_at,end_at) values ('${task}', '2099-01-05 10:00:00-03','2099-01-05 10:30:00-03')`);
await rejected("insert into torre_busy_blocks(start_at,end_at) values ('2099-01-05 10:15:00-03','2099-01-05 11:00:00-03')");
await db.exec(`update torre_tasks set status='waiting',waiting_for='Contato',follow_up_date='2099-01-06' where id='${task}'`);
assert.equal((await db.query('select count(*)::int as n from torre_scheduled_blocks')).rows[0].n,0);
await db.exec(`update torre_tasks set status='completed' where id='${task}'`);
assert.ok((await db.query('select completed_at from torre_tasks')).rows[0].completed_at);
await db.exec(`set request.jwt.claim.sub='${b}'`);
assert.equal((await db.query('select count(*)::int as n from torre_tasks')).rows[0].n,0);
assert.equal((await db.query(`update torre_tasks set title='Invasão' where id='${task}' returning id`)).rows.length,0);
await rejected("insert into torre_integration_accounts(provider) values ('google_tasks')");
await db.exec('reset role; set role anon');
await rejected('select * from torre_tasks');
console.log('PASS: migration PostgreSQL, RLS, isolamento entre usuários, espera, conclusão, reservas, conflitos e permissões de integração.');
await db.close();
