import {useEffect,useRef,useState} from 'react';
import {Bot,Send,RotateCcw,Check,MessageSquare,LoaderCircle,PanelLeft,PanelLeftClose,Plus,Search,X} from 'lucide-react';
import Markdown,{defaultUrlTransform} from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {agentFieldNames as fieldNames,agentValues as values,remarkAgentPresentation} from './agentPresentation';
import {supabase} from './supabase';
import {ensure,invoke,type Features} from './features';
import './agent.css';

type Operation={entity:'task'|'label';id:string;title:string;before:Record<string,unknown>|null;patch:Record<string,unknown>};
type ModelChoice='openrouter/free'|'google/gemini-2.5-flash';
type Run={id:string;conversation_id:string|null;message:string;mode:'analyze'|'execute';state:'processing'|'ready'|'answered'|'applied'|'undone'|'error';response:string;model:string|null;requested_model:ModelChoice;error:string|null;operations:Operation[];created_at:string};
type Conversation={conversation_id:string|null;title:string;updated_at:string;run_count:number};
const conversationKey=(id:string|null)=>id??'legacy';
function modelName(model:string|undefined){return model==='google/gemini-2.5-flash'?'Gemini 2.5 Flash · pago':'OpenRouter · gratuito';}
function AgentResponse({text,references,onTask,onLabel}:{text:string;references:Record<string,string>;onTask:(id:string)=>void;onLabel:(id:string)=>void}){
 return <div className="agent-response"><Markdown skipHtml remarkPlugins={[remarkGfm,[remarkAgentPresentation,{references}]]} urlTransform={url=>/^(task|label):[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(url)?url:defaultUrlTransform(url)} components={{
  a:({href,children})=>{const ref=/^(task|label):([0-9a-f-]{36})$/i.exec(href??'');if(ref)return <button type="button" className="agent-reference" onClick={()=>ref[1]==='task'?onTask(ref[2]):onLabel(ref[2])}>{children}</button>;return /^https?:\/\//i.test(href??'')?<a href={href} target="_blank" rel="noopener noreferrer">{children}</a>:<span>{children}</span>;},
  img:()=>null,table:({children})=><div className="agent-table-scroll"><table>{children}</table></div>
 }}>{text}</Markdown></div>;
}
export function AgentChat({userId,features,onRefresh,onTask,onLabel,onSettings}:{userId:string;features:Features;onRefresh:()=>void;onTask:(id:string)=>void;onLabel:(id:string)=>void;onSettings:()=>void}){
 const [runs,setRuns]=useState<Run[]>([]),[text,setText]=useState(''),[mode,setMode]=useState<'analyze'|'execute'>('analyze'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState(''),[historyOpen,setHistoryOpen]=useState(false),[search,setSearch]=useState(''),[moreConversations,setMoreConversations]=useState(false),[moreRuns,setMoreRuns]=useState(false),[olderBusy,setOlderBusy]=useState(false),[listBusy,setListBusy]=useState(false);
 const model:ModelChoice=features.ai?.default_model==='google/gemini-2.5-flash'?'google/gemini-2.5-flash':'openrouter/free';
 async function chooseModel(value:string){setError('');const ok=await features.run(()=>invoke('ai-default',{model:value}));if(!ok)setError('Não foi possível salvar o modelo padrão. Tente novamente.');}
 const locked=useRef(false),bottom=useRef<HTMLDivElement>(null),historyButton=useRef<HTMLButtonElement>(null),panel=useRef<HTMLElement>(null);const active=useRef(true),selection=useRef(''),loadVersion=useRef(0),listVersion=useRef(0);
 function selectConversation(id:string){selection.current=id;setSelected(id);setText('');setError('');setHistoryOpen(false);try{localStorage.setItem(`torre:${userId}:agent-conversation`,id);}catch{}historyButton.current?.focus();}
 function newConversation(){if(locked.current)return;selectConversation(crypto.randomUUID());}
 async function list(offset=0,query=search){const version=++listVersion.current;setListBusy(true);try{const {data}=await ensure(supabase.rpc('torre_agent_conversations',{p_offset:offset,p_query:query}));if(active.current&&version===listVersion.current){setConversations(current=>offset?[...current,...data]:data??[]);setMoreConversations((data?.length??0)===50);}return (data??[]) as Conversation[];}finally{if(active.current&&version===listVersion.current)setListBusy(false);}}
 async function load(older=false){const id=selection.current,version=++loadVersion.current;if(!id)return;let q=supabase.from('torre_agent_runs').select('id,conversation_id,message,mode,state,response,model,requested_model,error,operations,created_at').eq('user_id',userId);q=id==='legacy'?q.is('conversation_id',null):q.eq('conversation_id',id);const offset=older?runs.length:0;const {data}=await ensure(q.order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+29));if(active.current&&selection.current===id&&version===loadVersion.current){setRuns(current=>older?[...(data??[]).reverse() as Run[],...current]:(data??[]).reverse() as Run[]);setMoreRuns((data?.length??0)===30);}}
 async function initialize(){setLoading(true);setError('');try{const items=await list(0,'');if(!active.current)return;let saved='';try{saved=localStorage.getItem(`torre:${userId}:agent-conversation`)??'';}catch{}selectConversation(saved==='legacy'||/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(saved)?saved:items.length?conversationKey(items[0].conversation_id):crypto.randomUUID());}catch{if(active.current){setError('Não foi possível carregar as conversas.');setLoading(false);}}}
 useEffect(()=>{active.current=true;void initialize();return()=>{active.current=false;loadVersion.current++;listVersion.current++;};},[userId]);
 useEffect(()=>{if(!selected)return;let cancelled=false;setRuns([]);setMoreRuns(false);setLoading(true);void load().catch(()=>{if(active.current&&!cancelled)setError('Não foi possível carregar a conversa. Tente novamente.');}).finally(()=>{if(active.current&&!cancelled)setLoading(false);});return()=>{cancelled=true;};},[selected]);
 useEffect(()=>{if(!selected)return;const timer=setTimeout(()=>{void list(0,search).catch(()=>setError('Não foi possível buscar as conversas.'));},250);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{if(!olderBusy)bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[runs.length,busy,loading]);
 useEffect(()=>{if(historyOpen)panel.current?.querySelector<HTMLInputElement>('input')?.focus();},[historyOpen]);
 function closeHistory(){setHistoryOpen(false);historyButton.current?.focus();}
 async function action(kind:'agent-chat'|'agent-apply'|'agent-undo',run:Run){
  if(locked.current)return;locked.current=true;setBusy(run.id);setError('');
  try{
   const data=await invoke(kind,{runId:run.id,...(kind==='agent-chat'?{message:run.message,mode:run.mode,model:run.requested_model??'openrouter/free',conversationId:run.conversation_id??null}:{})});
   if(active.current)setRuns(current=>current.some(r=>r.id===run.id)?current.map(r=>r.id===run.id?data.run:r):[...current,data.run]);
   if(data.run.state==='applied'||data.run.state==='undone'){onRefresh();await features.load();}
   await list().catch(()=>{});
  }catch(e){if(active.current)setError((e as Error).message);await load().catch(()=>{});if(active.current&&selection.current===conversationKey(run.conversation_id))setRuns(current=>current.some(r=>r.id===run.id)?current.map(r=>r.id===run.id&&r.state==='processing'?{...r,state:'error',error:(e as Error).message}:r):[...current,{...run,state:'error',error:(e as Error).message}]);}
  finally{locked.current=false;if(active.current)setBusy('');}
 }
 function send(){if(!text.trim()||locked.current||loading||!selected||!features.ai?.has_key)return;const run:Run={id:crypto.randomUUID(),conversation_id:selected==='legacy'?null:selected,message:text.trim(),mode,state:'processing',response:'',model:null,requested_model:model,error:null,operations:[],created_at:new Date().toISOString()};setRuns(current=>[...current,run]);setText('');void action('agent-chat',run);}
 function showValue(key:string,value:unknown){if(value===null)return 'Remover';if(key==='archived_at')return 'Arquivar';if(key==='archived')return value?'Arquivar':'Restaurar';if(key==='label_ids')return (value as string[]).map(id=>features.labels.find(l=>l.id===id)?.name??runs.flatMap(r=>r.operations).find(o=>o.id===id)?.title??'Label').join(', ')||'Sem labels';return values[String(value)]??String(value);}
 const references:Record<string,string>={},prefixes=new Map<string,Set<string>>();
 const reference=(id:string,title:string)=>{const key=id.toLowerCase();references[key]=title;const prefix=key.slice(0,8);if(!prefixes.has(prefix))prefixes.set(prefix,new Set());prefixes.get(prefix)!.add(key);};
 for(const run of runs){for(const match of run.response.matchAll(/\[([^\]]+)\]\((?:task|label):([0-9a-f-]{36})\)/gi))reference(match[2],match[1]);for(const op of run.operations)reference(op.id,op.title);}
 for(const label of features.labels)reference(label.id,label.name);
 for(const [prefix,ids] of prefixes)if(ids.size===1)references[prefix]=references[[...ids][0]];
 const title=conversations.find(c=>conversationKey(c.conversation_id)===selected)?.title??runs[0]?.message??'Nova conversa';
 return <section className={'agent-chat'+(historyOpen?' history-open':'')} aria-label="Conversa com o agente" onKeyDown={e=>{if(e.key==='Escape'&&historyOpen){e.stopPropagation();closeHistory();}if(e.key==='Tab'&&historyOpen&&window.matchMedia('(max-width: 760px)').matches&&panel.current){const controls=Array.from(panel.current.querySelectorAll<HTMLElement>('button:not(:disabled),input'));const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
 {historyOpen&&<><button tabIndex={-1} className="agent-history-scrim" aria-label="Fechar histórico do agente" onClick={closeHistory}/><aside ref={panel} id="agent-conversations" className="agent-conversations" role={window.matchMedia('(max-width: 760px)').matches?'dialog':undefined} aria-modal={window.matchMedia('(max-width: 760px)').matches?true:undefined} aria-label="Histórico do agente"><div className="agent-panel-heading"><h2>Histórico do agente</h2><button type="button" aria-label="Recolher histórico do agente" onClick={closeHistory}><PanelLeftClose size={19}/></button></div><label className="agent-conversation-search"><Search size={16}/><input aria-label="Buscar conversa" placeholder="Buscar conversa…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Limpar busca de conversas" onClick={()=>setSearch('')}><X size={14}/></button>}</label><div className="agent-conversation-list" aria-busy={listBusy}>{conversations.map(c=><button key={conversationKey(c.conversation_id)} className={conversationKey(c.conversation_id)===selected?'active':''} aria-current={conversationKey(c.conversation_id)===selected?'true':undefined} disabled={!!busy||olderBusy} onClick={()=>selectConversation(conversationKey(c.conversation_id))} title={c.title}><MessageSquare size={16}/><span><strong>{c.title}</strong><small>{new Date(c.updated_at).toLocaleDateString('pt-BR',{day:'numeric',month:'short'})} · {c.run_count} pedido(s)</small></span></button>)}{!conversations.length&&!listBusy&&<p>{search?'Nenhuma conversa encontrada.':'Suas conversas aparecerão aqui.'}</p>}{moreConversations&&<button disabled={listBusy} onClick={()=>void list(conversations.length).catch(()=>setError('Não foi possível carregar mais conversas.'))}>Carregar mais conversas</button>}</div></aside></>}
 <div className="agent-workspace" inert={historyOpen&&window.matchMedia('(max-width: 760px)').matches}><header className="agent-header"><button ref={historyButton} type="button" className="agent-history-toggle" aria-expanded={historyOpen} aria-controls="agent-conversations" onClick={()=>historyOpen?closeHistory():setHistoryOpen(true)}><PanelLeft size={18}/><span>Histórico do agente</span></button><div className="agent-title"><h2 title={title}>{title}</h2><small>Modo IA</small></div><button type="button" className="agent-new" disabled={!!busy||loading||olderBusy} onClick={newConversation}><Plus size={17}/><span>Nova conversa</span></button><label className="agent-model-control"><span className="agent-sr-only">Modelo</span><select aria-label="Modelo da IA" aria-describedby="agent-model-description" value={model} disabled={!!busy||features.working} onChange={e=>void chooseModel(e.target.value)}><option value="openrouter/free">OpenRouter gratuito</option><option value="google/gemini-2.5-flash">Gemini 2.5 Flash — pago</option></select></label><label className="agent-mode"><span className="agent-sr-only">Modo</span><select aria-label="Modo da IA" value={mode} disabled={!!busy} onChange={e=>setMode(e.target.value as typeof mode)}><option value="analyze">Analisar</option><option value="execute">Executar pedido</option></select></label><p id="agent-model-description">{model==='openrouter/free'?'Padrão de toda a Torre: gratuito · disponibilidade e cota variáveis.':<>Padrão de toda a Torre: Gemini usa a mesma chave OpenRouter e cobra por tokens. <a href="https://openrouter.ai/google/gemini-2.5-flash" target="_blank" rel="noopener noreferrer">Consultar preços</a></>}</p></header>
 <div className="agent-history" aria-label="Histórico da conversa" aria-busy={loading||!!busy}>{loading?<p role="status">Carregando conversa…</p>:<>
 {moreRuns&&<button className="agent-older" disabled={olderBusy||!!busy} onClick={()=>{setOlderBusy(true);void load(true).catch(()=>setError('Não foi possível carregar pedidos anteriores.')).finally(()=>setOlderBusy(false));}}>{olderBusy?'Carregando…':'Carregar pedidos anteriores'}</button>}
 {!runs.length?<div className="agent-empty"><div className="agent-intro-icon"><Bot size={30}/></div><h2>Suas tarefas, em conversa</h2><p>Peça uma avaliação ou dê um comando para tarefas e labels.</p><small>As análises consultam sua conta inteira. Cada conversa tem seu próprio contexto.</small><div className="agent-suggestions" aria-label="Sugestões de pedidos">{['Avalie minhas tarefas e explique o que merece atenção.','Quais tarefas estão atrasadas?','Revise minhas labels e sugira melhorias.'].map(s=><button key={s} disabled={!!busy} onClick={()=>{setMode('analyze');setText(s);}}><MessageSquare size={16}/>{s}</button>)}</div></div>:runs.map(run=><article className="agent-turn" key={run.id}><div className="agent-user"><small>Você · {run.mode==='analyze'?'Analisar':'Executar pedido'} · {modelName(run.requested_model)}</small><p>{run.message}</p></div><div className="agent-answer"><small><Bot size={18}/> Torre IA</small>{busy===run.id?<p className="agent-working" role="status"><LoaderCircle size={16}/> {run.state==='ready'?'Aplicando pedido…':run.state==='applied'?'Desfazendo…':'Consultando suas tarefas e labels…'}</p>:<>
 {run.response&&<AgentResponse text={run.response} references={references} onTask={onTask} onLabel={onLabel}/>}
 {run.operations.length>0&&<><p className="agent-result" role="status">{run.state==='applied'?`Pedido aplicado: ${run.operations.length} registro(s).`:run.state==='undone'?'Pedido desfeito.':run.state==='ready'?'Proposta preparada. Confira as alterações antes de aplicar.':''}</p><details open={run.state==='ready'}><summary>{run.state==='ready'?'Revisar alterações':'Ver alterações'}</summary><ul className="agent-operations">{run.operations.map(op=><li key={op.id}><strong>{op.before?'Alterar':'Criar'} {op.entity==='task'?'tarefa':'label'}: {op.title}</strong><dl>{Object.entries(op.patch).map(([k,v])=><div key={k}><dt>{fieldNames[k]??k}</dt><dd>{showValue(k,v)}</dd></div>)}</dl></li>)}</ul></details>{run.state==='ready'&&<button className="primary" disabled={!!busy} onClick={()=>void action('agent-apply',run)}><Check size={16}/> Aplicar pedido</button>}{run.state==='applied'&&<><button disabled={!!busy} onClick={()=>void action('agent-undo',run)}><RotateCcw size={15}/> Desfazer pedido</button>{run.operations.some(o=>o.entity==='task')&&<small className="agent-footnote">Conclusões do Google ficam pendentes de sincronização. Desfazer não recria reservas e não reabre tarefas concluídas do Google.</small>}</> }</>}
 {run.error&&<p role="alert">{run.error}</p>}{(run.state==='error'||run.state==='processing')&&<button disabled={!!busy} onClick={()=>void action('agent-chat',run)}>Tentar novamente este pedido</button>}
 </>}</div></article>)} </>}<div ref={bottom}/></div>
 {!features.ai?.has_key&&<div className="notice"><p>Cadastre sua chave OpenRouter para conversar com o agente.</p><button onClick={onSettings}>Configurar IA</button></div>}
 {error&&<div className="notice" role="alert">{error}{!busy&&<button type="button" onClick={()=>{if(!selected){void initialize();return;}setLoading(true);setError('');void load().catch(()=>setError('Não foi possível carregar a conversa. Tente novamente.')).finally(()=>setLoading(false));}}>Atualizar conversa</button>}</div>}
 <form className="agent-composer" onSubmit={e=>{e.preventDefault();send();}}><label className="agent-input"><span className="agent-sr-only">Seu pedido</span><textarea rows={2} maxLength={4000} disabled={!!busy||loading} value={text} onChange={e=>setText(e.target.value)} placeholder="Pergunte sobre suas tarefas…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/></label><button type="submit" className="primary" disabled={!!busy||loading||!selected||!text.trim()||!features.ai?.has_key}><Send size={17}/>{busy?'Aguarde…':'Enviar'}</button><small>{mode==='analyze'?'Analisar responde sem fazer alterações.':'Executar pedido aplica comandos claros. Arquivamentos em lote passam por uma prévia.'} Enter para enviar · Shift + Enter para nova linha.</small></form></div></section>;
}
