import type {Label} from './features';
import {useState,type ReactNode} from 'react';
import {LayoutDashboard,ListTodo,CalendarDays,Settings,Search,Plus,Menu,X} from 'lucide-react';

type Props={account:ReactNode;labels:Label[];labelFilter:string[];onLabel:(id:string)=>void;children:ReactNode;page:string;area:string;query:string;pendingCount:number;onPage:(page:string)=>void;onArea:(area:string)=>void;onQuery:(query:string)=>void;onNew:()=>void};
export function AppShell({account,labels,labelFilter,onLabel,children,page,area,query,pendingCount,onPage,onArea,onQuery,onNew}:Props){
 const [menuOpen,setMenuOpen]=useState(false);
 const items=[...(import.meta.env.DEV?[{label:'Home',icon:LayoutDashboard}]:[]),{label:'Caixa de entrada',icon:ListTodo},{label:'Tarefas',icon:ListTodo},{label:'Planejamento',icon:CalendarDays},{label:'Configurações',icon:Settings}];
 return <div className="app-shell" onKeyDown={e=>{if(e.key==='Escape')setMenuOpen(false);}}><aside className={'sidebar '+(menuOpen?'is-open':'')} aria-label="Menu principal"><div className="sidebar-brand"><span className="brand-icon"><LayoutDashboard size={22}/></span><div><strong>Torre de Controle</strong></div><button className="close-menu" onClick={()=>setMenuOpen(false)} aria-label="Fechar menu"><X size={19}/></button></div><button className="sidebar-capture" onClick={()=>{onNew();setMenuOpen(false);}}><Plus size={18}/>Captura rápida</button><div className="sidebar-section">NAVEGAÇÃO</div><nav className="sidebar-nav">{items.filter(i=>i.label!=='Configurações').map(({label,icon:Icon})=><button key={label} className={page===label?'active':''} aria-current={page===label?'page':undefined} onClick={()=>{onPage(label);setMenuOpen(false);}}><Icon size={18}/><span>{label==='Planejamento'?'Agenda semanal':label==='Home'?'Home — experimental':label}</span>{label==='Tarefas'&&<span className="nav-count">{pendingCount}</span>}</button>)}</nav><div className="sidebar-section">LABELS</div><nav className="sidebar-nav"><button onClick={()=>onLabel('none')} className={labelFilter.includes('none')?'active':''}>Sem label</button>{labels.filter(l=>!l.archived).map(l=><button key={l.id} onClick={()=>onLabel(l.id)} className={labelFilter.includes(l.id)?'active':''}><span style={{color:l.color}}>●</span>{l.name}</button>)}</nav><div className="sidebar-bottom"><button className={page==='Configurações'?'active':''} onClick={()=>{onPage('Configurações');setMenuOpen(false);}} aria-current={page==='Configurações'?'page':undefined}><Settings size={18}/>Configurações</button><div className="sidebar-account" aria-label="Conta">{account}</div></div></aside>{menuOpen&&<button className="menu-scrim" onClick={()=>setMenuOpen(false)} aria-label="Fechar menu lateral"/>}<div className="app-content"><header className="app-topbar"><button className="mobile-menu" aria-label="Abrir menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><Menu size={21}/></button><div className="top-search"><Search size={18}/><input type="search" aria-label="Buscar tarefas" placeholder="Buscar tarefas…" value={query} onChange={e=>onQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>onQuery('')}><X size={16}/></button>}</div><div className="top-area" role="group" aria-label="Área das tarefas">{['Tudo','Pessoal','Profissional'].map(a=><button key={a} aria-pressed={area===a} onClick={()=>onArea(a)}>{a==='Tudo'?'Todas as áreas':a}</button>)}</div><button className="top-capture" aria-label="Captura rápida" onClick={onNew}><Plus size={17}/><span>Capturar</span></button></header>{children}</div></div>;
}
