import {priorities,type Priority} from './priority';
import {useState} from 'react';
import type {Task} from './task';
import type {Features} from './features';
export type BatchChange={kind:'priority';value:Priority}|{kind:'label';id:string;remove?:boolean}|{kind:'complete'}|{kind:'due';value:string}|{kind:'minutes';value:number}|{kind:'situation';value:'todo'|'waiting';waitingFor?:string;followUp?:string};
export function BulkActions({tasks,features,onClear,onApply,onClassify}:{tasks:Task[];features:Features;onClear:()=>void;onApply:(change:BatchChange)=>Promise<boolean>;onClassify:()=>Promise<boolean>}){
 const [priority,setPriority]=useState<Priority>('none');
 const [action,setAction]=useState('label'),[label,setLabel]=useState(''),[date,setDate]=useState(''),[minutes,setMinutes]=useState(30),[situation,setSituation]=useState<'todo'|'waiting'>('todo'),[waitingFor,setWaitingFor]=useState(''),[followUp,setFollowUp]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!tasks.length)return null;
 const google=tasks.some(t=>t.googleTaskId);const completed=tasks.some(t=>t.done);
 async function submit(){setError('');setBusy(true);try{if(action==='ai'){await onClassify();return;}if(action==='due'&&google)throw new Error('O prazo das tarefas importadas é editado no Google Tasks.');if(action==='situation'&&completed)throw new Error('Ajuste a situação de tarefas em aberto.');const change:BatchChange=action==='priority'?{kind:'priority',value:priority}:action==='complete'?{kind:'complete'}:action==='due'?{kind:'due',value:date}:action==='minutes'?{kind:'minutes',value:minutes}:action==='situation'?{kind:'situation',value:situation,waitingFor,followUp}:{kind:'label',id:label,remove:action==='remove-label'};await onApply(change);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="bulk-actions" aria-label="Ações em lote" onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy||features.working}><strong>{tasks.length} selecionada(s)</strong><button type="button" onClick={onClear}>Limpar seleção</button><label>Ação<select value={action} onChange={e=>{setAction(e.target.value);setError('');}}><option value="label">Adicionar label</option><option value="remove-label">Retirar label</option><option value="ai">Classificar labels por IA</option><option value="complete">Concluir</option><option value="due">Ajustar prazo</option><option value="priority">Ajustar prioridade</option><option value="minutes">Ajustar duração</option><option value="situation">Ajustar situação</option></select></label>{['label','remove-label'].includes(action)&&<label>Label<select required value={label} onChange={e=>setLabel(e.target.value)}><option value="">Selecione</option>{features.labels.filter(l=>!l.archived).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}{action==='priority'&&<label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value as Priority)}>{priorities.map(p=><option key={p.value} value={p.value}>{p.label}</option>)}</select></label>}{action==='due'&&<label>Prazo<input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Vazio retira o prazo.</small></label>}{action==='minutes'&&<label>Duração (min)<input type="number" min={5} max={480} step={5} required value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><small>Reservas existentes serão retiradas.</small></label>}{action==='situation'&&<><label>Situação<select value={situation} onChange={e=>setSituation(e.target.value as 'todo'|'waiting')}><option value="todo">A fazer</option><option value="waiting">Aguardando resposta</option></select></label>{situation==='waiting'&&<><label>De quem depende?<input required maxLength={180} value={waitingFor} onChange={e=>setWaitingFor(e.target.value)}/></label><label>Acompanhar em<input required type="date" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label></>}</>}{action==='ai'&&<small>A IA acrescenta somente labels existentes, preservando as atuais. Até 20 tarefas por vez.</small>}{action==='due'&&google&&<small>Para prazo, selecione somente tarefas criadas na Torre.</small>}<button className="primary" disabled={action==='ai'&&(!features.ai?.enabled||tasks.length>20)||action==='due'&&google||action==='situation'&&completed}>{busy?'Aplicando…':action==='ai'?'Classificar por IA':'Aplicar'}</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
