import {useRef,useState} from 'react';
import {invoke} from './features';
export function CaptureEvaluation({enabled}:{enabled:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<any[]>([]);const stop=useRef(false);
 async function evaluate(){setBusy(true);setResults([]);setMessage('Preparando avaliação…');stop.current=false;const output:any[]=[];let spent=0;
  try{for(let batch=0;batch<10&&!stop.current;batch++){const ids=Array.from({length:10},(_,i)=>batch*10+i+1);for(const profile of ['luna','gemini','free','legacy-free']){if(stop.current)continue;if(spent>.70){stop.current=true;setMessage('Avaliação encerrada antes do teto de US$ 1.');break;}setMessage(`Lote ${batch+1}/10 · ${profile} · custo informado US$ ${spent.toFixed(4)}`);try{const result=await invoke('capture-evaluate',{profile,ids});output.push(result);if(typeof result.audit?.cost==='number')spent+=result.audit.cost;else {output.push({profile,error:'Custo total não informado; avaliação interrompida para respeitar o orçamento.'});stop.current=true;}}catch(e){output.push({profile,ids,error:(e as Error).message});stop.current=true;setMessage('Comparação interrompida após uma falha. Uma chamada com erro pode ter custo; confira o uso no OpenRouter.');}setResults([...output]);}}
   if(!stop.current)setMessage(`Avaliação concluída · custo informado US$ ${spent.toFixed(4)}. Confira as falhas e os resultados antes de comparar qualidade.`);
  }finally{setBusy(false);}
 }
 const summary=[...new Set(results.map(r=>r.profile))].map(profile=>{const items=results.filter(r=>r.profile===profile),rows=items.flatMap(x=>x.rows??[]),checks=rows.flatMap((r:any)=>Object.values(r.fields??{}).filter(x=>typeof x==='boolean'));return {profile,cases:rows.length,correct:checks.filter(Boolean).length,total:checks.length,failures:items.filter(x=>x.error).length,cost:items.reduce((sum,x)=>sum+(x.audit?.cost??0),0)};});
 return <details className="capture-evaluation"><summary>Comparar modelos com textos fictícios</summary><p>Avalia 100 exemplos de datas, pessoas e classificação. Não cria tarefas nem envia suas capturas. Inclui chamadas pagas. Interrompe ao atingir US$ 0,70 informado, reservando margem para a chamada em andamento. O custo final deve ser conferido no OpenRouter.</p><button disabled={!enabled||busy} onClick={()=>void evaluate()}>Executar comparação de modelos</button>{busy&&<button onClick={()=>{stop.current=true;setMessage('Encerrando após a chamada atual…');}}>Parar comparação</button>}<p role="status">{message}</p>{summary.length>0&&<table><thead><tr><th>Modelo</th><th>Casos</th><th>Campos corretos</th><th>Falhas</th><th>US$ informado</th></tr></thead><tbody>{summary.map(s=><tr key={s.profile}><td>{s.profile}</td><td>{s.cases}</td><td>{s.correct}/{s.total}</td><td>{s.failures}</td><td>{s.cost.toFixed(4)}</td></tr>)}</tbody></table>}{results.length>0&&<><details><summary>Resultados completos</summary><pre>{JSON.stringify(results,null,2)}</pre></details><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(results,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='torre-comparacao-modelos.json';a.click();URL.revokeObjectURL(url);}}>Baixar resultados</button></>}</details>;
}
