import {useEffect,useState,type ReactNode} from 'react';
import type {User} from '@supabase/supabase-js';
import {supabase} from './supabase';
export function Cloud({children}:{children:(user:User,account:ReactNode)=>ReactNode}){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data,error})=>{setUser(data.session?.user??null);setMessage(error?.message??'');setReady(true);});const {data}=supabase.auth.onAuthStateChange((_,session)=>{setUser(session?.user??null);setReady(true);});return()=>data.subscription.unsubscribe();},[]);
 if(!ready)return <main>Carregando sua sessão…</main>;
 if(user)return <>{children(user,<><span className="account-email" title={user.email}>{user.email}</span><button disabled={pending} onClick={async()=>{setPending(true);setMessage('');try{const {error}=await supabase.auth.signOut();if(error)setMessage(error.message);}catch{setMessage('Não foi possível sair. Tente novamente.');}finally{setPending(false);}}}>{pending?'Saindo…':'Sair'}</button>{message&&<span role="alert">{message}</span>}</>)}</>;
 return <main className="auth-page"><section className="card"><div className="card-head"><h1>Torre de Controle</h1></div><form className="form-body" onSubmit={async e=>{e.preventDefault();setPending(true);setMessage('');const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)setMessage(error.message);setPending(false);}}><label>E-mail<input name="email" type="email" autoComplete="username" required/></label><label>Senha<input name="password" type="password" autoComplete="current-password" minLength={6} required/></label><button className="primary" disabled={pending}>Entrar</button><button type="button" disabled={pending} onClick={async e=>{const form=e.currentTarget.form!;if(!form.reportValidity())return;setPending(true);const f=new FormData(form);const {error}=await supabase.auth.signUp({email:String(f.get('email')),password:String(f.get('password')),options:{emailRedirectTo:'https://samuelveronez.github.io/torre/'}});setMessage(error?.message??'Conta criada. Confirme o e-mail recebido e depois entre aqui.');setPending(false);}}>Criar conta</button><button type="button" disabled={pending} onClick={async e=>{const email=String(new FormData(e.currentTarget.form!).get('email')??'').trim();if(!email){setMessage('Preencha seu e-mail para reenviar a confirmação.');return;}setPending(true);const {error}=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:'https://samuelveronez.github.io/torre/'}});setMessage(error?.message??'Confirmação reenviada. Use o e-mail mais recente.');setPending(false);}}>Reenviar confirmação</button><p role="status">{message}</p></form></section></main>;
}
