import {Tabs,TabsList,TabsTrigger,TabsContent} from './components/ui/tabs';
import {hiddenReservationCount} from './reservationVisibility';
import {HiddenReservations} from './components/Experience';
import {priorityRank} from './priority';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,CalendarDays,Plus,Clock} from 'lucide-react';
import type {Features} from './features';
import type {Task} from './task';
import {DayTaskGroup} from './DayTaskGroup';
import {TaskRow} from './TaskRow';
import {dateKey,dayGroups,newest} from './taskView';
import {slotAt,reservationWarning} from './scheduling';
import {AllDayAgenda,TimedAgenda,eventsForDay} from './AgendaEvents';
type Props={allTasks:Task[];onClearFilters:()=>void;showDeclined:boolean;onShowDeclined:(value:boolean)=>void;date:Date;onDate:(d:Date)=>void;tasks:Task[];features:Features;newIds:string[];onOpen:(id:string)=>void;onComplete:(id:string)=>void;onPlan:(id:string)=>void;onPlace:(id:string,day:string,time:string)=>Promise<boolean|undefined>;onCapture:()=>void;onWeek:(suggest:boolean)=>void};
const clock=(value:number)=>new Date(value).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
export default function Home({allTasks,onClearFilters,showDeclined,onShowDeclined,date,onDate,tasks,features,newIds,onOpen,onComplete,onPlan,onPlace,onCapture,onWeek}:Props){
 const [focusOrder,setFocusOrder]=useState('current');
 const [choosing,setChoosing]=useState(false),[planning,setPlanning]=useState(''),[tab,setTab]=useState('tasks'),[now,setNow]=useState(new Date()),[drag,setDrag]=useState<number|null>(null),[dragId,setDragId]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setPlanning('');setDrag(null);},[dateKey(date)]);
 const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const day=dateKey(date);
 const groups=dayGroups(tasks,date);const eligible=tasks.filter(t=>!t.done&&!t.at&&t.situation!=='waiting').sort(newest);
 const events=eventsForDay(date,features.events,features.calendars,showDeclined).sort((a,b)=>Number(b.all_day)-Number(a.all_day)||Date.parse(a.start_at)-Date.parse(b.start_at));const stale=features.google?.connected&&!features.fresh;
 const agendaProps={date,events:features.events,calendars:features.calendars,tasks,showDeclined,onOpen};
 const dragTask=tasks.find(t=>t.id===(dragId||planning));const dragAt=new Date(day+'T'+`${String(Math.floor((drag??420)/60)).padStart(2,'0')}:${String((drag??420)%60).padStart(2,'0')}`);
 const warning=dragTask?reservationWarning(dragTask,dragAt,tasks,events.map(e=>({start:Date.parse(e.start_at)>=start.getTime()?new Date(e.start_at).getHours()+new Date(e.start_at).getMinutes()/60:0,end:Date.parse(e.end_at)>=end.getTime()?24:new Date(e.end_at).getHours()+new Date(e.end_at).getMinutes()/60,blocks:e.blocks_time,title:e.title}))):'';
 const move=(n:number)=>{const d=new Date(date);d.setDate(d.getDate()+n);onDate(d);};
 const place=async(id:string,minute:number)=>{if(id&&tasks.some(t=>t.id===id&&!t.done&&t.situation!=='waiting')){const saved=await onPlace(id,day,`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`);if(saved)setPlanning('');setDrag(null);setDragId('');}};
 const row=(t:Task)=><TaskRow key={t.id} task={t} features={features} referenceDay={day} onOpen={onOpen} onComplete={onComplete} onPlan={onPlan} isNew={newIds.includes(t.id)}/>;
 function section(title:string,rows:Task[],collapse=false){return <DayTaskGroup key={day+title} title={title} rows={focusOrder==='priority'?[...rows].sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)):rows} renderRow={row} collapse={collapse}/>;}
 return <Tabs value={tab} onValueChange={setTab}><div className="day-heading"><div className="day-navigation"><button aria-label="Dia anterior" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><label className="date-control"><CalendarDays size={16}/><input aria-label="Data de Meu dia" type="date" value={day} onChange={e=>{if(e.target.value)onDate(new Date(e.target.value+'T12:00'));}}/></label><button aria-label="Próximo dia" onClick={()=>move(1)}><ChevronRight size={18}/></button><button onClick={()=>onDate(new Date())}>Hoje</button></div><h2>{date.toLocaleDateString('pt-BR',{weekday:'short',day:'numeric',month:'long'})}</h2></div><HiddenReservations count={hiddenReservationCount(allTasks,tasks,[date])} onClear={onClearFilters}/><div className="daily-actions"><button className="day-choose-primary" onClick={()=>setChoosing(!choosing)} aria-expanded={choosing}><Plus size={16}/>Escolher tarefas</button><button onClick={()=>onWeek(true)}><Clock size={16}/>Sugerir horários</button><button onClick={()=>onWeek(false)}>Agenda semanal</button><button className="primary" onClick={onCapture}>Capturar</button></div><TabsList className="daily-tabs" aria-label="Visão de Meu dia"><TabsTrigger value="tasks">Tarefas</TabsTrigger><TabsTrigger value="agenda">Agenda</TabsTrigger></TabsList>
 <div className={`home-layout daily-view show-${tab}`}><TabsContent value="tasks" forceMount asChild><section className="home-tasks" aria-label="Tarefas do dia" onDragStartCapture={e=>setDragId((e.target as HTMLElement).closest<HTMLElement>('[data-task-id]')?.dataset.taskId??'')} onDragEnd={()=>{setDragId('');setDrag(null);}}><div className="day-focus-heading"><h2>Foco do dia</h2><small>{new Set([...groups.reserved,...groups.due,...groups.late,...groups.follow].map(t=>t.id)).size} tarefas</small><label className="focus-order">Ordenar<select value={focusOrder} onChange={e=>setFocusOrder(e.target.value)}><option value="current">Ordem atual</option><option value="priority">Prioridade</option></select></label></div>{choosing&&<section className="day-group day-choice"><h2>Pendências para planejar <span className="count">{eligible.length}</span></h2><p>Arraste para um horário ou use Reservar. Os filtros atuais se aplicam.</p><div className="day-choice-rows">{eligible.map(t=><div key={t.id} className={planning===t.id?'chosen-task':''}><TaskRow task={t} features={features} referenceDay={day} onOpen={onOpen} onComplete={onComplete} draggable onPlan={id=>{setPlanning(id);setTab('agenda');}}/></div>)}{!eligible.length&&<p>Nenhuma pendência com estes filtros.</p>}</div></section>}{section('Reservadas no dia',groups.reserved)}{section('Com prazo no dia',groups.due)}{section('Atrasadas',groups.late,true)}{section('Acompanhamentos',groups.follow,true)}</section></TabsContent>
 <TabsContent value="agenda" forceMount asChild><aside className="home-agenda daily-agenda" aria-label="Agenda do dia"><div className="agenda-sync"><small>{features.google?.connected?(features.fresh?'Agenda atualizada':'Agenda desatualizada'):'Reservas locais'}</small><button disabled={features.working} onClick={()=>void features.sync()}>Atualizar</button></div>{stale&&<p role="status" className="agenda-stale">A agenda pode ter compromissos ainda não sincronizados. Você pode reservar manualmente.</p>}{planning&&<p className="planning-hint">Escolha um horário para {tasks.find(t=>t.id===planning)?.title}. <button onClick={()=>onPlan(planning)}>Usar formulário</button> <button onClick={()=>setPlanning('')}>Cancelar</button></p>}
 <section className="today-commitments" aria-label="Compromissos de hoje"><h3>Compromissos de hoje <span className="count">{events.length}</span></h3>{!events.length?<p>{features.google?.connected?'Nenhum compromisso disponível para este dia.':'Conecte uma agenda em Configurações para ver seus compromissos.'}</p>:<><ul>{events.slice(0,3).map(e=><li key={e.calendar_id+e.id}><time>{e.all_day?'Dia inteiro':new Date(e.start_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><span>{e.title}</span></li>)}</ul>{events.length>3&&<details><summary>Ver todos ({events.length})</summary><ul>{events.slice(3).map(e=><li key={e.calendar_id+e.id}><time>{e.all_day?'Dia inteiro':new Date(e.start_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><span>{e.title}</span></li>)}</ul></details>}</>}</section>
 <label className="declined-control"><input type="checkbox" checked={showDeclined} onChange={e=>onShowDeclined(e.target.checked)}/>Mostrar recusados</label><AllDayAgenda {...agendaProps}/>
 <div className="daily-time-scroll"><div className="daily-time-axis">{Array.from({length:16},(_,i)=><span key={i} style={{top:i*48}}>{String(i+7).padStart(2,'0')}:00</span>)}</div><div className="daily-time-body" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';setDrag(slotAt(e.clientY,e.currentTarget.getBoundingClientRect().top));const box=e.currentTarget.parentElement?.getBoundingClientRect();if(box&&e.clientY>box.bottom-40)e.currentTarget.parentElement!.scrollTop+=12;if(box&&e.clientY<box.top+40)e.currentTarget.parentElement!.scrollTop-=12;}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(null);}} onDrop={e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),slotAt(e.clientY,e.currentTarget.getBoundingClientRect().top));}}>
 {Array.from({length:60},(_,i)=><button className="day-quarter" key={i} aria-label={`Reservar em ${day} às ${String(Math.floor((420+i*15)/60)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`} disabled={!planning} onClick={()=>place(planning,420+i*15)}/>)}
 <TimedAgenda {...agendaProps} onReserveAt={planning?minute=>void place(planning,minute):undefined}/>
 {drag!==null&&<div className="daily-drop-preview" style={{top:(drag-420)/60*48}}>Soltar às {Math.floor(drag/60)}:{String(drag%60).padStart(2,'0')}{warning&&<small>{warning}</small>}</div>}
 {dateKey(now)===day&&now.getHours()>=7&&now.getHours()<22&&<div className="current-time" style={{top:(now.getHours()+now.getMinutes()/60-7)*48}}><span>{clock(now.getTime())}</span></div>}
 </div></div><small className="day-help">Clique em uma reserva para editar. Reservas manuais respeitam jornada e duração e podem sobrepor compromissos.</small></aside></TabsContent></div>
 </Tabs>;
}
