import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,CalendarDays,Plus,Clock} from 'lucide-react';
import type {Features} from './features';
import type {Task} from './task';
import {TaskRow} from './TaskRow';
import {dateKey,dayGroups,newest} from './taskView';
import {slotAt} from './scheduling';
type Props={date:Date;onDate:(d:Date)=>void;tasks:Task[];features:Features;newIds:string[];onOpen:(id:string)=>void;onComplete:(id:string)=>void;onPlan:(id:string)=>void;onPlace:(id:string,day:string,time:string)=>Promise<boolean|undefined>;onCapture:()=>void;onWeek:(suggest:boolean)=>void};
const clock=(value:number)=>new Date(value).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
export default function Home({date,onDate,tasks,features,newIds,onOpen,onComplete,onPlan,onPlace,onCapture,onWeek}:Props){
 const [choosing,setChoosing]=useState(false),[planning,setPlanning]=useState(''),[tab,setTab]=useState('tasks'),[now,setNow]=useState(new Date()),[drag,setDrag]=useState<number|null>(null),[eventInfo,setEventInfo]=useState<string|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setPlanning('');setDrag(null);setEventInfo(null);},[dateKey(date)]);
 const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const day=dateKey(date);
 const groups=dayGroups(tasks,date);const eligible=tasks.filter(t=>!t.done&&!t.at&&t.situation!=='waiting').sort(newest);
 const events=features.events.filter(e=>features.calendars.some(c=>c.id===e.calendar_id&&c.selected)&&Date.parse(e.start_at)<end.getTime()&&Date.parse(e.end_at)>start.getTime()).map(e=>({...e,color:features.calendars.find(c=>c.id===e.calendar_id)?.color??'#64748b'}));
 const event=eventInfo?events.find(e=>e.calendar_id+e.id===eventInfo):undefined;const stale=features.google?.connected&&!features.fresh;
 const move=(n:number)=>{const d=new Date(date);d.setDate(d.getDate()+n);onDate(d);};
 const place=async(id:string,minute:number)=>{if(id&&eligible.some(t=>t.id===id)){const saved=await onPlace(id,day,`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`);if(saved)setPlanning('');setDrag(null);}};
 const row=(t:Task)=><TaskRow key={t.id} task={t} features={features} onOpen={onOpen} onComplete={onComplete} onPlan={onPlan} isNew={newIds.includes(t.id)}/>;
 function section(title:string,rows:Task[],collapse=false){return collapse?<details className="day-group"><summary>{title} <span className="count">{rows.length}</span></summary>{rows.length?rows.map(row):<p className="section-empty">Nenhuma tarefa.</p>}</details>:<section className="day-group"><h2>{title} <span className="count">{rows.length}</span></h2>{rows.length?rows.map(row):<p className="section-empty">Nenhuma tarefa.</p>}</section>;}
 return <><div className="daily-actions"><button onClick={()=>setChoosing(!choosing)} aria-expanded={choosing}><Plus size={16}/>Escolher tarefas</button><button onClick={()=>onWeek(true)}><Clock size={16}/>Sugerir horários</button><button onClick={()=>onWeek(false)}>Agenda semanal</button><button className="primary" onClick={onCapture}>Capturar</button></div><div className="daily-tabs" role="group" aria-label="Visão de Meu dia"><button aria-pressed={tab==='tasks'} onClick={()=>setTab('tasks')}>Tarefas</button><button aria-pressed={tab==='agenda'} onClick={()=>setTab('agenda')}>Agenda</button></div>
 <div className={`home-layout daily-view show-${tab}`}><section className="home-tasks" aria-label="Tarefas do dia">{choosing&&<section className="day-group day-choice"><h2>Pendências para planejar <span className="count">{eligible.length}</span></h2><p>Arraste para um horário ou use Reservar. Os filtros atuais se aplicam.</p><div className="day-choice-rows">{eligible.map(t=><div key={t.id} className={planning===t.id?'chosen-task':''}><TaskRow task={t} features={features} onOpen={onOpen} onComplete={onComplete} draggable onPlan={id=>{setPlanning(id);setTab('agenda');}}/></div>)}{!eligible.length&&<p>Nenhuma pendência com estes filtros.</p>}</div></section>}{section('Reservadas no dia',groups.reserved)}{section('Com prazo no dia',groups.due)}{section('Atrasadas',groups.late,true)}{section('Acompanhamentos',groups.follow,true)}</section>
 <aside className="home-agenda daily-agenda" aria-label="Agenda do dia"><div className="day-navigation"><button aria-label="Dia anterior" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><label className="date-control"><CalendarDays size={16}/><input aria-label="Data de Meu dia" type="date" value={day} onChange={e=>{if(e.target.value)onDate(new Date(e.target.value+'T12:00'));}}/></label><button aria-label="Próximo dia" onClick={()=>move(1)}><ChevronRight size={18}/></button><button onClick={()=>onDate(new Date())}>Hoje</button></div><h2>{date.toLocaleDateString('pt-BR',{weekday:'short',day:'numeric',month:'long'})}</h2><div className="agenda-sync"><small>{features.google?.connected?(features.fresh?'Agenda atualizada':'Agenda desatualizada'):'Reservas locais'}</small><button disabled={features.working} onClick={()=>void features.sync()}>Atualizar</button></div>{stale&&<p role="status" className="agenda-stale">Atualize antes de reservar.</p>}{planning&&<p className="planning-hint">Escolha um horário para {tasks.find(t=>t.id===planning)?.title}. <button onClick={()=>onPlan(planning)}>Usar formulário</button> <button onClick={()=>setPlanning('')}>Cancelar</button></p>}
 <div className="all-day-events">{events.filter(e=>e.all_day).map(e=><button key={e.calendar_id+e.id} onClick={()=>setEventInfo(e.calendar_id+e.id)} style={{borderLeftColor:e.color}}>Dia inteiro · {e.title||'Ocupado'}</button>)}</div>
 <div className="daily-time-scroll"><div className="daily-time-axis">{Array.from({length:16},(_,i)=><span key={i} style={{top:i*48}}>{String(i+7).padStart(2,'0')}:00</span>)}</div><div className="daily-time-body" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';setDrag(slotAt(e.clientY,e.currentTarget.getBoundingClientRect().top));const box=e.currentTarget.parentElement?.getBoundingClientRect();if(box&&e.clientY>box.bottom-40)e.currentTarget.parentElement!.scrollTop+=12;if(box&&e.clientY<box.top+40)e.currentTarget.parentElement!.scrollTop-=12;}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(null);}} onDrop={e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),slotAt(e.clientY,e.currentTarget.getBoundingClientRect().top));}}>
 {Array.from({length:60},(_,i)=><button className="day-quarter" key={i} aria-label={`Reservar em ${day} às ${String(Math.floor((420+i*15)/60)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`} disabled={!planning||!!stale} onClick={()=>place(planning,420+i*15)}/>)}
 {events.filter(e=>!e.all_day).map(e=>{const a=Math.max(Date.parse(e.start_at),start.getTime()+7*3600000),b=Math.min(Date.parse(e.end_at),start.getTime()+22*3600000);if(b<=a)return null;return <button className="timeline-event google-event" key={e.calendar_id+e.id} style={{top:(a-start.getTime()-7*3600000)/3600000*48,height:Math.max(24,(b-a)/3600000*48),borderLeftColor:e.color}} onClick={()=>setEventInfo(e.calendar_id+e.id)}><strong>{e.title||'Ocupado'}</strong><small>{clock(Date.parse(e.start_at))} – {clock(Date.parse(e.end_at))} · Google</small></button>;})}
 {groups.reserved.map(t=>{const a=Math.max(Date.parse(t.at!),start.getTime()+7*3600000),b=Math.min(Date.parse(t.at!)+t.minutes*60000,start.getTime()+22*3600000);return b>a?<button className={`timeline-event ${t.area==='Pessoal'?'personal':'professional'}`} key={t.id} style={{top:(a-start.getTime()-7*3600000)/3600000*48,height:Math.max(28,(b-a)/3600000*48)}} onClick={()=>onOpen(t.id)}><strong>{t.title}</strong><small>{clock(Date.parse(t.at!))} · {t.minutes} min</small></button>:<button className="outside-hours" key={t.id} onClick={()=>onOpen(t.id)}>{clock(Date.parse(t.at!))} · {t.title}</button>;})}
 {drag!==null&&<div className="daily-drop-preview" style={{top:(drag-420)/60*48}}>Soltar às {Math.floor(drag/60)}:{String(drag%60).padStart(2,'0')}</div>}
 {dateKey(now)===day&&now.getHours()>=7&&now.getHours()<22&&<div className="current-time" style={{top:(now.getHours()+now.getMinutes()/60-7)*48}}><span>{clock(now.getTime())}</span></div>}
 </div></div><small className="day-help">Clique em uma reserva para editar. Horários livres respeitam jornada, duração e compromissos.</small></aside></div>
 {event&&<><button className="event-info-backdrop" aria-label="Fechar compromisso" onClick={()=>setEventInfo(null)}/><div className="event-info" role="dialog" aria-modal="true" aria-label="Compromisso Google" onKeyDown={e=>{if(e.key==='Escape')setEventInfo(null);if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector<HTMLElement>('button')?.focus();}}}><h2>{event.title||'Ocupado'}</h2><p>{event.all_day?'Dia inteiro':`${clock(Date.parse(event.start_at))} – ${clock(Date.parse(event.end_at))}`}</p>{event.location&&<p>{event.location}</p>}<p>Consulta · Google Agenda</p><button autoFocus onClick={()=>setEventInfo(null)}>Fechar</button></div></>}</>;
}
