import {useState,type ReactNode} from 'react';
import type {Features} from './features';
import type {Task} from './task';

const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const time=(value:number)=>new Date(value).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
export default function Home({children,date,onDate,tasks,area,features}:{children:ReactNode;date:Date;onDate:(date:Date)=>void;tasks:Task[];area:string;features:Features}){
 const [month,setMonth]=useState(new Date(date.getFullYear(),date.getMonth(),1));
 const first=new Date(month);first.setDate(1-(first.getDay()+6)%7);
 const cells=Array.from({length:42},(_,i)=>{const d=new Date(first);d.setDate(d.getDate()+i);return d;});
 const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);
 const events=features.events.filter(e=>features.calendars.some(c=>c.id===e.calendar_id&&c.selected)&&Date.parse(e.start_at)<end.getTime()&&Date.parse(e.end_at)>start.getTime()).map(e=>({id:e.calendar_id+e.id,title:e.title,location:e.location,start:Date.parse(e.start_at),end:Date.parse(e.end_at),allDay:e.all_day,color:features.calendars.find(c=>c.id===e.calendar_id)?.color??'#64748b',source:features.calendars.find(c=>c.id===e.calendar_id)?.name??'Google'}));
 const reservations=tasks.filter(t=>!t.done&&t.at&&(area==='Tudo'||t.area===area)&&Date.parse(t.at)<end.getTime()&&Date.parse(t.at)+t.minutes*60000>start.getTime()).map(t=>({id:t.id,title:t.title,location:null,start:Date.parse(t.at!),end:Date.parse(t.at!)+t.minutes*60000,allDay:false,color:t.area==='Pessoal'?'#6b3fa0':'#0176d3',source:`Reserva · ${t.area}`}));
 const items=[...events,...reservations].sort((a,b)=>Number(b.allDay)-Number(a.allDay)||a.start-b.start);
 return <div className="home-layout"><section className="home-tasks" aria-label="Tarefas da Home">{children}</section><aside className="card home-agenda" aria-label="Agenda do dia"><div className="card-head"><h2>Agenda do dia</h2><button onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));onDate(now);}}>Hoje</button></div><div className="home-agenda-body"><div className="month-heading"><button aria-label="Mês anterior" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button aria-label="Próximo mês" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="mini-month" role="group" aria-label="Escolher dia">{['S','T','Q','Q','S','S','D'].map((day,i)=><span key={i} aria-hidden="true">{day}</span>)}{cells.map(d=><button key={key(d)} aria-label={d.toLocaleDateString('pt-BR',{dateStyle:'full'})} aria-pressed={key(d)===key(date)} className={`${d.getMonth()!==month.getMonth()?'other-month ':''}${key(d)===key(new Date())?'today':''}`} onClick={()=>{onDate(d);if(d.getMonth()!==month.getMonth())setMonth(new Date(d.getFullYear(),d.getMonth(),1));}}>{d.getDate()}</button>)}</div><h3>{date.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</h3><div className="agenda-sync"><small>{features.google?.connected?(features.fresh?'Agenda atualizada':'Agenda desatualizada'):'Reservas de tarefas'}</small>{features.google?.connected&&<button disabled={features.working} onClick={()=>void features.sync()}>Atualizar</button>}</div>{features.google?.connected&&!features.fresh&&<p className="agenda-stale">Os compromissos podem estar desatualizados. Atualize antes de planejar.</p>}{!items.length&&<p>Nenhum compromisso ou reserva neste dia.</p>}<div className="day-events">{items.map(item=><article key={item.id} className="day-event" style={{borderLeftColor:item.color}}><small>{item.allDay?'Dia inteiro':`${time(Math.max(item.start,start.getTime()))} – ${time(Math.min(item.end,end.getTime()))}`}</small><h3>{item.title}</h3><small>{item.source}</small>{item.location&&<p>{item.location}</p>}</article>)}</div></div></aside></div>;
}
