import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {TaskList} from './TaskList';
type Area='Pessoal'|'Profissional';
type Task={id:string;title:string;area:Area;minutes:number;due:string;source:string;done:boolean;at?:string};
type Hours={enabled:boolean;start:number;end:number};
const days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const monday=(d:Date)=>{const r=new Date(d);r.setHours(0,0,0,0);r.setDate(r.getDate()-(r.getDay()+6)%7);return r;};
const plus=(d:Date,n:number)=>{const r=new Date(d);r.setDate(r.getDate()+n);return r;};
const today=dateKey(new Date());
const initial:Task[]=[{id:'a',title:'Revisar prioridades da semana',area:'Profissional',minutes:30,due:today,source:'Google Tasks · demo',done:false},{id:'b',title:'Organizar documentos da casa',area:'Pessoal',minutes:45,due:'',source:'Torre',done:false},{id:'c',title:'Preparar pauta da próxima reunião',area:'Profissional',minutes:60,due:dateKey(plus(new Date(),2)),source:'Google Tasks · demo',done:false},{id:'d',title:'Agendar revisão do carro',area:'Pessoal',minutes:15,due:today,source:'Torre',done:false}];
const defaultHours=Array.from({length:7},(_,i)=>({enabled:i>0&&i<6,start:9,end:i===5?17:18}));
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function App(){
 const [tasks,setTasks]=useState<Task[]>(()=>read('torre-tasks-v1',initial));
 const [hours,setHours]=useState<Hours[]>(()=>read('torre-hours-v1',defaultHours));
 const [week,setWeek]=useState(monday(new Date()));const [focus,setFocus]=useState('');
 const [area,setArea]=useState('Tudo');const [limit,setLimit]=useState(0);const [page,setPage]=useState('Tarefas');
 const [modal,setModal]=useState<'new'|'plan'|null>(null);const [selected,setSelected]=useState('');const [message,setMessage]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{localStorage.setItem('torre-tasks-v1',JSON.stringify(tasks));},[tasks]);
 useEffect(()=>{localStorage.setItem('torre-hours-v1',JSON.stringify(hours));},[hours]);
 useEffect(()=>{if(modal){dialog.current?.showModal();}else dialog.current?.close();},[modal]);
 useEffect(()=>{const expire=()=>setTasks(ts=>ts.map(t=>t.at&&!t.done&&new Date(t.at).getTime()+t.minutes*60000<Date.now()?{...t,at:undefined}:t));expire();const timer=setInterval(expire,60000);return()=>clearInterval(timer);},[]);
 const dates=Array.from({length:7},(_,i)=>plus(week,i));const visibleDates=focus?dates.filter(d=>dateKey(d)===focus):dates;
 const active=tasks.filter(t=>!t.done&&(area==='Tudo'||t.area===area));
 const pending=active.filter(t=>!t.at&&(!limit||t.minutes<=limit)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
 function busy(d:Date){return d.getDay()>0&&d.getDay()<6?[{start:10,end:11},{start:14,end:15.5}]:[];}
 function plan(id:string,day:string,time:string){const t=tasks.find(x=>x.id===id);if(!t)return;const at=new Date(`${day}T${time}`);const start=at.getHours()+at.getMinutes()/60,end=start+t.minutes/60,h=hours[at.getDay()];const work=h.enabled&&start>=h.start&&end<=h.end;const personal=!h.enabled||end<=h.start||start>=h.end;
 if(at.getTime()<Date.now()){setMessage('Escolha um horário futuro.');return;}
 if(start<7||end>22){setMessage('Escolha um horário entre 7h e 22h.');return;}
 if((t.area==='Profissional'&&!work)||(t.area==='Pessoal'&&!personal)){setMessage('Esse horário não corresponde à área da tarefa. Ajuste a jornada em Configurações.');return;}
 if(busy(at).some(b=>start<b.end&&end>b.start)||tasks.some(x=>x.id!==id&&!x.done&&x.at&&at.getTime()<new Date(x.at).getTime()+x.minutes*60000&&at.getTime()+t.minutes*60000>new Date(x.at).getTime())){setMessage('Esse intervalo já está ocupado. Escolha outra janela.');return;}
 setTasks(ts=>ts.map(x=>x.id===id?{...x,at:at.toISOString()}:x));setModal(null);setMessage('Tarefa reservada na agenda.');}
 function complete(id:string){setTasks(ts=>ts.map(t=>t.id===id?{...t,done:true,at:undefined}:t));setMessage('Concluída nesta demonstração. Google Tasks ainda não está conectado.');}
 function openPlan(id:string){setSelected(id);setMessage('');setModal('plan');}
 return <><header><span className="brand">T</span><strong>Torre de Controle</strong><span className="demo">Validação de telas</span><span className="avatar">SV</span></header><nav>{['Tarefas','Planejamento','Configurações'].map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}</nav><main><div className="heading"><div><small>Seu tempo, com intenção</small><h1>{page==='Tarefas'?'Tudo o que você precisa fazer':page==='Planejamento'?'Uma semana que cabe na sua vida':'Sua rotina de trabalho'}</h1><p>{page==='Tarefas'?'Capture, consulte e conclua suas tarefas. Reserve um horário quando fizer sentido.':page==='Planejamento'?'Reúna as pendências. Encontre espaço. Escolha o que fazer.':'Defina a jornada para separar as janelas profissionais e pessoais.'}</p></div><button className="primary" onClick={()=>{setMessage('');setModal('new');}}>＋ Nova tarefa</button></div><div className="notice">Demonstração com dados fictícios · Google e calendário não conectados · Alterações salvas apenas neste navegador.</div>
 {page==='Tarefas'?<TaskList tasks={tasks} onComplete={complete} onReopen={id=>{setTasks(ts=>ts.map(t=>t.id===id?{...t,done:false,at:undefined}:t));setMessage('Tarefa reaberta.');}} onPlan={openPlan} onUnplan={id=>{setTasks(ts=>ts.map(t=>t.id===id?{...t,at:undefined}:t));setMessage('Reserva retirada. A tarefa continua na lista.');}} onNew={()=>{setMessage('');setModal('new');}}/>:page==='Planejamento'?<><div className="summary"><div><small>Pendências</small><strong>{tasks.filter(t=>!t.done&&!t.at).length}</strong></div><div><small>Reservadas na semana</small><strong>{tasks.filter(t=>!t.done&&t.at&&dates.some(d=>dateKey(new Date(t.at!))===dateKey(d))).length}</strong></div><div><small>Seu ritual diário</small><strong>5–15 <span>min</span></strong></div></div><div className="toolbar"><div className="tabs" role="group" aria-label="Área">{['Tudo','Pessoal','Profissional'].map(a=><button aria-pressed={area===a} className={area===a?'active':''} key={a} onClick={()=>setArea(a)}>{a}</button>)}</div><button onClick={()=>{setWeek(monday(new Date()));setFocus('');}}>Hoje</button><button aria-label="Semana anterior" onClick={()=>{setWeek(plus(week,-7));setFocus('');}}>‹</button><strong>{week.toLocaleDateString('pt-BR',{day:'numeric',month:'short'})} – {plus(week,6).toLocaleDateString('pt-BR',{day:'numeric',month:'short'})}</strong><button aria-label="Próxima semana" onClick={()=>{setWeek(plus(week,7));setFocus('');}}>›</button><select aria-label="Foco da agenda" value={focus} onChange={e=>setFocus(e.target.value)}><option value="">Semana inteira</option>{dates.map(d=><option key={dateKey(d)} value={dateKey(d)}>{days[d.getDay()]} {d.getDate()}</option>)}</select></div>
 <div className="workspace"><section className="card calendar"><div className="card-head"><h2>Agenda da semana</h2><small>Ocupado · agenda de demonstração</small></div><div className="calendar-scroll"><div className={'grid '+(focus?'focused':'')} style={{gridTemplateColumns:`48px repeat(${visibleDates.length}, minmax(110px,1fr))`}}><div className="time-head">Hora</div>{visibleDates.map(d=><button className={'day-head '+(dateKey(d)===today?'current':'')} key={dateKey(d)} onClick={()=>setFocus(focus?'':dateKey(d))}>{days[d.getDay()]} <b>{d.getDate()}</b></button>)}<div className="time-axis">{Array.from({length:15},(_,i)=><span key={i} style={{top:i*48}}>{i+7}:00</span>)}</div>{visibleDates.map(d=><div className="day-column" key={dateKey(d)}>{Array.from({length:15},(_,i)=><button key={i} className="slot" aria-label={`Planejar em ${dateKey(d)} às ${i+7} horas`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();plan(e.dataTransfer.getData('text/plain'),dateKey(d),`${String(i+7).padStart(2,'0')}:00`);}} onClick={()=>{if(selected)plan(selected,dateKey(d),`${String(i+7).padStart(2,'0')}:00`);else setMessage('Use Planejar na tarefa ou arraste para um horário.');}}/>)}{busy(d).map((b,i)=><div className="event busy" key={i} style={{top:(b.start-7)*48,height:(b.end-b.start)*48}}><b>Ocupado</b><small>{b.start}:00 – {Math.floor(b.end)}:{b.end%1?'30':'00'}</small></div>)}{active.filter(t=>t.at&&dateKey(new Date(t.at))===dateKey(d)).map(t=>{const dt=new Date(t.at!);return <div className={'event '+(t.area==='Pessoal'?'personal':'professional')} key={t.id} style={{top:(dt.getHours()+dt.getMinutes()/60-7)*48,height:Math.max(34,t.minutes/60*48)}}><button className="event-title" onClick={()=>openPlan(t.id)} title={t.title}>{t.title}</button><small>{dt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {t.minutes} min · {t.area}</small><div className="event-actions"><button onClick={()=>complete(t.id)} aria-label={`Concluir ${t.title}`}>✓</button><button onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,at:undefined}:x))} aria-label={`Voltar ${t.title} às pendências`}>↩</button></div></div>;})}</div>)}</div></div><div className="legend"><span>● Profissional</span><span className="purple">● Pessoal</span><span className="gray">● Ocupado</span><small>Arraste ou use Planejar. Clique no dia para focar.</small></div></section>
 <aside className="card"><div className="card-head"><h2>Pendências <span className="count">{pending.length}</span></h2></div><div className="pending-body"><label>Cabe em até<select value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value="0">Qualquer duração</option>{[15,30,45,60,90,120].map(n=><option value={n} key={n}>{n} minutos</option>)}</select></label>{pending.length===0&&<div className="empty"><h3>Nenhuma pendência aqui</h3><p>Capture uma tarefa ou ajuste os filtros.</p><button onClick={()=>{setArea('Tudo');setLimit(0);}}>Limpar filtros</button></div>}{pending.map(t=><article draggable onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} className="task" key={t.id}><span className={'pill '+(t.area==='Pessoal'?'purple':'')}>{t.area}</span><h3>{t.title}</h3><p>{t.minutes} min <span>· {t.source}</span></p>{t.due&&<small className={t.due<=today?'urgent':''}>{t.due<today?'Atrasada · ':t.due===today?'Hoje · ':'Prazo · '}{new Date(t.due+'T12:00').toLocaleDateString('pt-BR')}</small>}<div className="task-actions"><button onClick={()=>openPlan(t.id)}>Planejar</button><button onClick={()=>complete(t.id)}>Concluir</button></div></article>)}</div></aside></div></>:<section className="card settings"><div className="card-head"><h2>Jornada semanal</h2></div><div className="settings-body">{hours.map((h,i)=><div className="hours-row" key={i}><label><input type="checkbox" checked={h.enabled} onChange={e=>setHours(hs=>hs.map((x,j)=>i===j?{...x,enabled:e.target.checked}:x))}/>{days[i]}</label><input aria-label={`Início ${days[i]}`} type="time" step="3600" disabled={!h.enabled} value={`${String(h.start).padStart(2,'0')}:00`} onChange={e=>{const n=Number(e.target.value.slice(0,2));if(n<h.end)setHours(hs=>hs.map((x,j)=>i===j?{...x,start:n}:x));}}/><span>até</span><input aria-label={`Fim ${days[i]}`} type="time" step="3600" disabled={!h.enabled} value={`${String(h.end).padStart(2,'0')}:00`} onChange={e=>{const n=Number(e.target.value.slice(0,2));if(n>h.start)setHours(hs=>hs.map((x,j)=>i===j?{...x,end:n}:x));}}/></div>)}<p>Alterações salvas automaticamente. Desmarque os dias sem trabalho. Os horários iniciais são exemplos.</p><h3>Conexões previstas</h3><p>Google Tasks: importar e concluir. Calendário: disponibilidade sem conteúdo. Banco Supabase: sincronização entre dispositivos. Ainda não conectados nesta validação.</p></div></section>}
 <footer>Torre de Controle · Planejar com clareza <span>Protótipo 0.1</span></footer></main><div className="status" role="status">{message&&<><span>{message}</span><button aria-label="Fechar mensagem" onClick={()=>setMessage('')}>×</button></>}</div>
 <dialog ref={dialog} onCancel={()=>setModal(null)} onClose={()=>setModal(null)}><form key={modal} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(modal==='new'){setTasks(ts=>[...ts,{id:crypto.randomUUID(),title:String(f.get('title')).trim(),area:f.get('area') as Area,minutes:Number(f.get('minutes')),due:String(f.get('due')||''),source:'Torre',done:false}]);setModal(null);setMessage('Tarefa adicionada às pendências.');}else plan(selected,String(f.get('day')),String(f.get('time')));}}><div className="card-head"><h2>{modal==='new'?'Capturar tarefa':'Reservar um horário'}</h2><button type="button" aria-label="Fechar diálogo" onClick={()=>setModal(null)}>×</button></div><div className="form-body">{modal==='new'?<><label>O que precisa ser feito?<input autoFocus required name="title" maxLength={180} placeholder="Ex.: revisar documento"/></label><label>Área<select name="area"><option>Pessoal</option><option>Profissional</option></select></label><label>Duração estimada (minutos)<input name="minutes" type="number" min="5" max="480" step="5" defaultValue="30" required/></label><label>Prazo (opcional)<input name="due" type="date"/></label></>:<><p>{tasks.find(t=>t.id===selected)?.title}</p><label>Dia<input autoFocus name="day" type="date" defaultValue={focus||today} required min={today}/></label><label>Horário<input name="time" type="time" defaultValue="19:00" required/></label><small>Respeita a área, a jornada e os intervalos ocupados.</small></>}</div><div className="dialog-message" role="status">{message}</div><div className="modal-footer"><button type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="primary" type="submit">{modal==='new'?'Adicionar tarefa':'Reservar horário'}</button></div></form></dialog></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
