import {ChevronRight,Clock,GripVertical} from 'lucide-react';
import type {Task} from './task';
import type {Features} from './features';
import {writeTaskDrag} from './taskDrag';
import {includedAt} from './taskView';
export function TaskRow({task:t,features,onOpen,onComplete,onReopen,onPlan,isNew=false,draggable=true,selected,onSelect}:{task:Task;features:Features;onOpen:(id:string)=>void;onComplete:(id:string)=>void;onReopen?:(id:string)=>void;onPlan?:(id:string)=>void;isNew?:boolean;draggable?:boolean;selected?:boolean;onSelect?:(id:string)=>void}){
 return <article data-task-id={t.id} className={`task-row ${t.done?'is-done':''} ${isNew?'new-task':''}`} draggable={draggable} onDragStart={e=>{writeTaskDrag(e.dataTransfer,[t.id]);const ghost=document.createElement('div');ghost.className='task-drag-ghost';ghost.textContent=`${t.title} · ${t.minutes} min`;document.body.appendChild(ghost);e.dataTransfer.setDragImage(ghost,12,12);setTimeout(()=>ghost.remove(),0);}}>
 {draggable&&<span className="task-grip" title="Arraste para uma label ou horário" aria-hidden="true"><GripVertical size={16}/></span>}{onSelect&&<input className="task-select" title="Selecionar para ações em lote" type="checkbox" checked={!!selected} aria-label={`Selecionar ${t.title}`} onChange={()=>onSelect(t.id)}/>}<input className="task-check" type="checkbox" checked={t.done} disabled={!!t.googleTaskId&&t.done||t.done&&!onReopen} aria-label={`${t.done?'Reabrir':'Concluir'} ${t.title}`} onChange={()=>t.done?onReopen?.(t.id):onComplete(t.id)}/>
 <div className="task-row-content"><button className="task-title" aria-label={`Editar ${t.title}`} onClick={()=>onOpen(t.id)}>{t.title}</button><div className="task-meta"><span className={'pill '+(t.area==='Pessoal'?'purple':'')}>{t.area}</span><span>{t.minutes} min</span>{t.labelIds?.map(id=>{const l=features.labels.find(l=>l.id===id);return l?<span key={id} className="label-chip" style={{borderColor:l.color}}>{l.name}</span>:null;})}{t.situation==='waiting'&&<span>Aguardando · {t.waitingFor}</span>}{t.due&&<span>Prazo · {new Date(t.due+'T12:00').toLocaleDateString('pt-BR')}</span>}{t.followUp&&t.situation==='waiting'&&<span>Acompanhar · {new Date(t.followUp+'T12:00').toLocaleDateString('pt-BR')}</span>}{t.at&&<span>Reserva · {new Date(t.at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</span>}<span className="task-created" title={t.googleTaskId?'Data de inclusão na Torre, não de criação no Google.':undefined}>Incluída · {includedAt(t.createdAt)}</span>{isNew&&<strong className="new-badge">Nova</strong>}{t.completionPending&&<span>Conclusão pendente</span>}{t.syncError&&<span role="alert">{t.syncError}</span>}</div></div>
 {onPlan&&!t.done&&t.situation!=='waiting'&&<button className="row-plan" aria-label={`Reservar ${t.title}`} onClick={()=>onPlan(t.id)}><Clock size={15}/><span>{t.at?'Reagendar':'Reservar'}</span></button>}<button className="details-arrow" aria-label={`Abrir ${t.title}`} onClick={()=>onOpen(t.id)}><ChevronRight size={18}/></button></article>;
}
