import {Button} from './components/ui/button';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from './components/ui/dropdown-menu';
import {MoreHorizontal} from 'lucide-react';
import {priorities} from './priority';
import {GripVertical} from 'lucide-react';
import type {Task} from './task';
import type {Features} from './features';
import {writeTaskDrag} from './taskDrag';
import {includedAt} from './taskView';
export function TaskRow({task:t,features,onOpen,onComplete,onReopen,onPlan,isNew=false,draggable=true,selected,onSelect,referenceDay}:{task:Task;features:Features;onOpen:(id:string)=>void;onComplete:(id:string)=>void;onReopen?:(id:string)=>void;onPlan?:(id:string)=>void;isNew?:boolean;draggable?:boolean;selected?:boolean;onSelect?:(id:string)=>void;referenceDay?:string}){
 return <article data-task-id={t.id} className={`task-row ${t.done?'is-done':''} ${isNew?'new-task':''} ${onSelect?'is-selecting':''} ${selected?'is-selected':''}`} draggable={draggable} onDragStart={e=>{writeTaskDrag(e.dataTransfer,[t.id]);const ghost=document.createElement('div');ghost.className='task-drag-ghost';ghost.textContent=`${t.title} · ${t.minutes} min`;document.body.appendChild(ghost);e.dataTransfer.setDragImage(ghost,12,12);setTimeout(()=>ghost.remove(),0);}}>
 {draggable&&<span className="task-grip" title="Arraste para uma label ou horário" aria-hidden="true"><GripVertical size={16}/></span>}{onSelect&&<label className="task-select" title="Selecionar para ações em lote"><input className="task-select-input" title="Selecionar para ações em lote" type="checkbox" checked={!!selected} aria-label={`Selecionar ${t.title}`} onChange={()=>onSelect(t.id)}/></label>}<label className="task-complete-target"><input className="task-check" type="checkbox" checked={t.done} disabled={!!t.googleTaskId&&t.done||t.done&&!onReopen} aria-label={`${t.done?'Reabrir':'Concluir'} ${t.title}`} onChange={()=>t.done?onReopen?.(t.id):onComplete(t.id)}/></label>
 <div className="task-row-content"><button className="task-title" aria-label={`Editar ${t.title}`} onClick={()=>onOpen(t.id)}>{t.title}</button><div className="task-meta"><span className={'pill '+(t.area==='Pessoal'?'purple':'')}>{t.area}</span><span>{t.minutes} min</span>{t.priority&&t.priority!=='none'&&<span className={`task-priority-indicator priority-${t.priority}`} aria-label={`Prioridade ${priorities.find(p=>p.value===t.priority)?.label}`}>{priorities.find(p=>p.value===t.priority)?.label}</span>}{t.situation==='waiting'&&<span>Aguardando · {t.waitingFor}</span>}{t.due&&<span className={referenceDay&&t.due<referenceDay?"task-due-overdue":undefined}>{referenceDay&&t.due<referenceDay?"Atrasada":"Prazo"} · {new Date(t.due+'T12:00').toLocaleDateString('pt-BR')}</span>}{t.followUp&&t.situation==='waiting'&&<span className={referenceDay&&t.followUp<=referenceDay?"task-follow-due":undefined}>Acompanhar · {new Date(t.followUp+'T12:00').toLocaleDateString('pt-BR')}</span>}{t.at&&<span className={referenceDay?"task-reserved":undefined}>Reserva · {new Date(t.at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',...(referenceDay?{year:'numeric' as const}:{}),hour:'2-digit',minute:'2-digit'})}</span>}<span className="task-created" title={t.googleTaskId?'Data de inclusão na Torre, não de criação no Google.':undefined}>Incluída · {includedAt(t.createdAt)}</span>{isNew&&<strong className="new-badge">Nova</strong>}{t.completionPending&&<span>Conclusão pendente</span>}{t.syncError&&<span role="alert">{t.syncError}</span>}<div className="task-labels">{t.labelIds?.map(id=>{const l=features.labels.find(l=>l.id===id);return l?<span key={id} className="label-chip" style={{borderColor:l.color}}>{l.name}</span>:null;})}</div></div></div>
 <div className="row-actions"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Ações de ${t.title}`}><MoreHorizontal size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={()=>onOpen(t.id)}>Alterar prioridade</DropdownMenuItem><DropdownMenuItem onSelect={()=>onOpen(t.id)}>Editar tarefa</DropdownMenuItem>{onPlan&&!t.done&&t.situation!=='waiting'&&<DropdownMenuItem onSelect={()=>onPlan(t.id)}>{t.at?'Reagendar':'Reservar horário'}</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div></article>;
}
