import {useState} from 'react';

type Task={id:string;title:string;area:'Pessoal'|'Profissional';minutes:number;due:string;source:string;done:boolean;at?:string};
type Props={tasks:Task[];area:string;query:string;onClearFilters:()=>void;onComplete:(id:string)=>void;onReopen:(id:string)=>void;onPlan:(id:string)=>void;onUnplan:(id:string)=>void;onNew:()=>void};

export function TaskList({tasks,area,query,onClearFilters,onComplete,onReopen,onPlan,onUnplan,onNew}:Props){

 const [status,setStatus]=useState('Pendentes');

 const [sort,setSort]=useState('Prazo');
 const today=new Date();today.setHours(0,0,0,0);
 const filtered=tasks.filter(t=>(area==='Tudo'||t.area===area)&&(status==='Todas'||(status==='Concluídas'?t.done:!t.done))&&t.title.toLocaleLowerCase('pt-BR').includes(query.trim().toLocaleLowerCase('pt-BR'))).sort((a,b)=>sort==='Duração'?a.minutes-b.minutes:sort==='Nome'?a.title.localeCompare(b.title,'pt-BR'):(a.due||'9999').localeCompare(b.due||'9999'));
 return <><div className="summary"><div><small>Em aberto</small><strong>{tasks.filter(t=>!t.done).length}</strong></div><div><small>Sem horário reservado</small><strong>{tasks.filter(t=>!t.done&&!t.at).length}</strong></div><div><small>Concluídas</small><strong>{tasks.filter(t=>t.done).length}</strong></div></div>
 <section className="card task-list"><div className="list-toolbar"><div className="list-context"><strong>{area==='Tudo'?'Todas as áreas':area}</strong><small>{query?`Resultados para “${query}”`:'Todas as suas tarefas, com ou sem horário reservado.'}</small></div><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['Pendentes','Concluídas','Todas'].map(s=><option key={s}>{s}</option>)}</select></label><label>Ordenar por<select value={sort} onChange={e=>setSort(e.target.value)}>{['Prazo','Duração','Nome'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 <div className="card-head"><h2>{status} <span className="count">{filtered.length}</span></h2><small>Conclua por aqui. Reservar horário é opcional.</small></div>
 <div className="task-rows">{filtered.map(t=>{const due=t.due?new Date(t.due+'T00:00'):null;return <article key={t.id} className={'task-row '+(t.done?'is-done':'')}><input className="task-check" type="checkbox" checked={t.done} aria-label={`${t.done?'Reabrir':'Concluir'} ${t.title}`} onChange={()=>t.done?onReopen(t.id):onComplete(t.id)}/><div className="task-row-content"><h3>{t.title}</h3><div className="task-meta"><span className={'pill '+(t.area==='Pessoal'?'purple':'')}>{t.area}</span><span>{t.minutes} min</span><span>{t.source}</span>{due&&<span className={!t.done&&due<=today?'urgent':''}>{due<today?'Prazo vencido':due.getTime()===today.getTime()?'Prazo hoje':'Prazo'} · {due.toLocaleDateString('pt-BR')}</span>}</div>{!t.done&&t.at&&<small className="scheduled-label">Reservada · {new Date(t.at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small>}</div><div className="task-row-actions">{t.done?<button onClick={()=>onReopen(t.id)}>Reabrir</button>:<><button className="primary" onClick={()=>onComplete(t.id)}>Concluir</button><button onClick={()=>onPlan(t.id)}>{t.at?'Reagendar':'Reservar horário'}</button>{t.at&&<button onClick={()=>onUnplan(t.id)}>Retirar da agenda</button>}</>}</div></article>;})}</div>
 {filtered.length===0&&<div className="list-empty"><h3>{query||area!=='Tudo'?'Nenhuma tarefa com esses filtros':status==='Concluídas'?'Você ainda não concluiu tarefas':'Sua lista está em dia'}</h3><p>{query||area!=='Tudo'?'Ajuste a busca ou a área para ver outras tarefas.':'Capture o que precisa fazer e conclua quando terminar.'}</p>{query||area!=='Tudo'?<button onClick={onClearFilters}>Limpar filtros</button>:<button onClick={onNew}>＋ Nova tarefa</button>}</div>}</section></>;
}
