import {useEffect,useState} from 'react';
import {supabase} from './supabase';

async function telegram(action:string,fields:Record<string,unknown>={}){
 const {data:{session}}=await supabase.auth.getSession();
 if(!session)throw new Error('Entre na Torre.');
 const response=await fetch('https://nvxwqrpztecrvrxoddxf.supabase.co/functions/v1/torre-telegram-settings',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...fields})});
 const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'Não foi possível salvar o Telegram.'),{code:data.code,testAfter:data.testAfter});return data;
}
type Delivery={digest_date:string;state:string;sent_at:string|null;error:string|null};
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export function TelegramSettings({userId}:{userId:string}){
 const [name,setName]=useState('torre_veronez_bot'),[token,setToken]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(true),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 const [linked,setLinked]=useState(false),[enabled,setEnabled]=useState(false),[weekdays,setWeekdays]=useState<number[]>([0,1,2,3,4,5,6]),[sendTime,setSendTime]=useState('21:00'),[link,setLink]=useState(''),[last,setLast]=useState<Delivery|null>(null);
 const [testAfter,setTestAfter]=useState<string|null>(null),[now,setNow]=useState(Date.now());
 const remaining=Math.max(0,Math.ceil(((testAfter?Date.parse(testAfter):0)-now)/1000));
 useEffect(()=>{if(!testAfter)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[testAfter]);
 function apply(data:any){setName(data.botName||'torre_veronez_bot');setSaved(data.hasToken);setLinked(data.linked);setEnabled(data.enabled);setWeekdays(data.weekdays);setSendTime(data.sendTime);setLast(data.last);setTestAfter(data.testAfter||null);setNow(Date.now());setLoaded(true);}
 useEffect(()=>{let active=true;setBusy(true);setLoaded(false);setToken('');telegram('status').then(data=>{if(active)apply(data);}).catch(()=>{if(active){setMessage('Não foi possível carregar as configurações. Reabra esta seção para tentar novamente.');setFailed(true);}}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[userId]);
 useEffect(()=>{
  if(!link||linked)return;
  let active=true,inFlight=false;const expires=Date.now()+10*60000;
  const check=async()=>{if(!active||inFlight||document.visibilityState==='hidden')return;if(Date.now()>expires){setLink('');setMessage('O link expirou. Clique em Vincular meu Telegram para gerar outro.');return;}inFlight=true;try{const data=await telegram('status');if(active&&data.linked){setLinked(true);setLink('');setFailed(false);setMessage('Chat vinculado. Você já pode enviar um resumo de teste.');}}catch{/* Keep the manual refresh available during network interruptions. */}finally{inFlight=false;}};
  const timer=window.setInterval(()=>void check(),5000);const onFocus=()=>void check();window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onFocus);
  return()=>{active=false;window.clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onFocus);};
 },[link,linked,userId]);
 async function run(action:string,fields:Record<string,unknown>={},success='Configurações salvas.'){
  setBusy(true);setFailed(false);setMessage('');try{const data=await telegram(action,fields);if(action==='test'){
   if(data.delivered!==true)throw new Error('O Telegram não confirmou a entrega. Confira o chat antes de tentar novamente.');
   setTestAfter(data.testAfter||new Date(Date.now()+60000).toISOString());setNow(Date.now());setMessage(success);
   try{const status=await telegram('status');setLinked(status.linked);setLast(status.last);setTestAfter(status.testAfter||data.testAfter||null);}catch{setMessage(success+' Não foi possível atualizar o estado da tela; a entrega já foi confirmada.');}
  }else if(action==='link'){setLink(data.url);setMessage('Abra o link abaixo e toque em Iniciar. O link vale por 10 minutos.');}else{if(action==='save'||action==='remove'){setToken('');setLink('');}apply(await telegram('status'));setMessage(success);}}catch(e){const error=e as Error&{code?:string;testAfter?:string};if(error.code==='TEST_COOLDOWN'){setTestAfter(error.testAfter||null);setNow(Date.now());setLinked(true);}if(error.code==='CHAT_NOT_LINKED')setLinked(false);setFailed(true);setMessage(error.message);}finally{setBusy(false);}
 }
 return <section className="card settings" aria-busy={busy}><div className="card-head"><h2>Telegram</h2></div><div className="settings-body">
  <form onSubmit={e=>{e.preventDefault();void run('save',{botName:name,token});}}><p>Cadastre o bot que será usado pela Torre de Controle.</p><fieldset disabled={busy||!loaded} className="telegram-fields"><label>Nome do bot<input value={name} onChange={e=>setName(e.target.value)} required maxLength={33} placeholder="@torre_veronez_bot" autoCapitalize="none" spellCheck={false}/></label><label>Token do BotFather<input type="password" value={token} onChange={e=>setToken(e.target.value)} required={!saved} maxLength={256} placeholder={saved?'Token salvo · preencha para substituir':'Cole o token fornecido pelo BotFather'} autoComplete="new-password" spellCheck={false}/></label><small>{saved?'Token armazenado com segurança. Deixe vazio para mantê-lo.':'O token não será exibido após salvar.'}</small><div className="toolbar"><button className="primary" type="submit">Salvar credenciais</button>{saved&&<button type="button" onClick={()=>void run('remove',{},'Credenciais removidas e lembrete desativado.')}>Remover credenciais</button>}</div></fieldset></form>
  <div className="telegram-connection"><h3>Seu chat</h3><p>{linked?'Chat vinculado à sua conta.':'Vincule seu chat para receber os resumos da sua conta.'}</p><div className="toolbar"><button disabled={busy||!saved} onClick={()=>void run('link')}>{linked?'Vincular outro chat':'Vincular meu Telegram'}</button><button disabled={busy||!saved} onClick={()=>void run('status',{},'Estado da conexão atualizado.')}>Atualizar conexão</button></div>{link&&<p><a href={link} target="_blank" rel="noreferrer">Abrir bot e vincular meu chat</a></p>}</div>
  <form onSubmit={e=>{e.preventDefault();void run('schedule',{enabled,weekdays,sendTime},'Lembrete salvo.');}}><h3>Resumo diário com IA</h3><p>Fechamento do dia do envio e preparação do dia seguinte, com tarefas concluídas, pendências, acompanhamentos e agenda disponível na Torre.</p><fieldset disabled={busy||!saved||!loaded} className="telegram-fields"><label className="telegram-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Ativar envio automático</label><div><p>Dias de envio</p><div className="telegram-weekdays" role="group" aria-label="Dias de envio">{days.map((day,index)=><label key={day}><input type="checkbox" checked={weekdays.includes(index)} onChange={e=>setWeekdays(current=>e.target.checked?[...current,index]:current.filter(d=>d!==index))}/>{day}</label>)}</div></div><label>Horário de envio<input type="time" required value={sendTime} onChange={e=>setSendTime(e.target.value)}/></label><small>Horário de Brasília · envio normalmente em até um minuto após o horário escolhido. O site pode estar fechado.</small><div className="toolbar"><button type="submit" className="primary" disabled={!weekdays.length}>Salvar lembrete</button><button type="button" disabled={!linked||remaining>0} aria-describedby={!linked?'telegram-send-help':undefined} onClick={()=>void run('test',{},'Resumo de teste enviado ao seu Telegram.')}>{remaining>0?`Aguarde ${remaining}s`:'Enviar resumo de teste'}</button></div>{!linked&&<small id="telegram-send-help">Para liberar o envio, clique em Vincular meu Telegram, abra o link e toque em Iniciar no bot. O vínculo será reconhecido automaticamente ao voltar; você também pode clicar em Atualizar conexão.</small>}</fieldset><p>A IA usa a chave OpenRouter cadastrada em Configurações → IA. O resumo reflete os dados já registrados e a última sincronização da agenda.</p></form>
  {last&&<p>Último envio automático ({new Date(last.digest_date+'T12:00:00').toLocaleDateString('pt-BR')}): {{sent:'Enviado',generating:'Gerando resumo',sending:'Enviando',error:'Falha',uncertain:'Sem confirmação de entrega'}[last.state]||last.state}{last.error&&` · ${last.error}`}</p>}
  {busy&&<p role="status">Processando…</p>}<p role={failed?'alert':'status'} className={failed?'settings-feedback failed':'settings-feedback'}>{message}</p>
 </div></section>;
}
