import {useEffect,useState} from 'react';
import {supabase} from './supabase';

async function telegram(action:string,fields:Record<string,string>={}){
 const {data:{session}}=await supabase.auth.getSession();
 if(!session)throw new Error('Entre na Torre.');
 const response=await fetch('https://nvxwqrpztecrvrxoddxf.supabase.co/functions/v1/torre-telegram-settings',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...fields})});
 const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível salvar o Telegram.');return data;
}
export function TelegramSettings({userId}:{userId:string}){
 const [name,setName]=useState('torre_veronez_bot'),[token,setToken]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(true),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;setBusy(true);setLoaded(false);setToken('');telegram('status').then(data=>{if(active){setName(data.botName||'torre_veronez_bot');setSaved(data.hasToken);setLoaded(true);}}).catch(()=>{if(active){setMessage('Não foi possível carregar as configurações. Reabra esta seção para tentar novamente.');setFailed(true);}}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[userId]);
 async function submit(remove=false){setBusy(true);setFailed(false);setMessage('');try{const data=await telegram(remove?'remove':'save',{botName:name,token});setSaved(data.hasToken);if(!remove)setName(data.botName);setToken('');setMessage(remove?'Credenciais removidas.':'Configurações do Telegram salvas.');}catch(e){setFailed(true);setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="card settings"><div className="card-head"><h2>Telegram</h2></div><form className="settings-body" onSubmit={e=>{e.preventDefault();void submit();}} aria-busy={busy}><p>Cadastre o bot que será usado pela Torre de Controle.</p><fieldset disabled={busy||!loaded} className="telegram-fields"><label>Nome do bot<input value={name} onChange={e=>setName(e.target.value)} required maxLength={33} placeholder="@torre_veronez_bot" autoCapitalize="none" spellCheck={false}/></label><label>Token do BotFather<input type="password" value={token} onChange={e=>setToken(e.target.value)} required={!saved} maxLength={256} placeholder={saved?'Token salvo · preencha para substituir':'Cole o token fornecido pelo BotFather'} autoComplete="new-password" spellCheck={false}/></label><small>{saved?'Token armazenado com segurança. Deixe vazio para mantê-lo.':'O token será armazenado com segurança e não será exibido após salvar.'}</small><div className="toolbar"><button className="primary" type="submit">{busy?'Salvando…':'Salvar Telegram'}</button>{saved&&<button type="button" onClick={()=>void submit(true)}>Remover credenciais</button>}</div></fieldset><p role={failed?'alert':'status'} className={failed?'settings-feedback failed':'settings-feedback'}>{message}</p><p>Este cadastro guarda as credenciais. Recebimento de mensagens e notificações ainda não estão ativados.</p></form></section>;
}
