import {useEffect,useRef,useState} from 'react';
import type {Task} from './task';
import {invoke,type Features} from './features';
export type Placement={taskId:string;start:string;end:string;reason:string};
type Proposal={id:string;placements:Placement[];unplaced:string[];expires_at:string};
const localInput=(value:string)=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
export function WeekPlanner({tasks,week,features,onPreview,onApplied}:{tasks:Task[];week:Date;features:Features;onPreview:(rows:Placement[])=>void;onApplied:()=>void}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[accepted,setAccepted]=useState<string[]>([]),[instruction,setInstruction]=useState(''),[proposal,setProposal]=useState<Proposal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const revision=useRef(0);
 const key=week.toISOString();
 useEffect(()=>{revision.current++;setProposal(null);setSelected([]);setAccepted([]);onPreview([]);setBusy(false);},[key]);
 useEffect(()=>()=>{revision.current++;},[]);
 const eligible=tasks.filter(t=>!t.done&&!t.at&&t.situation!=='waiting');
 const eligibleKey=eligible.map(t=>t.id).sort().join(',');
 useEffect(()=>{const ids=new Set(eligibleKey.split(','));setSelected(current=>current.filter(id=>ids.has(id)));},[eligibleKey]);
 async function suggest(){setBusy(true);setError('');const rev=revision.current;try{const end=new Date(week);end.setDate(end.getDate()+7);const data:Proposal=await invoke('plan-propose',{taskIds:selected,start:week.toISOString(),end:end.toISOString(),instruction});if(rev!==revision.current)return;setProposal(data);setAccepted(data.placements.map(p=>p.taskId));onPreview(data.placements);}catch(e){if(rev===revision.current)setError((e as Error).message);}finally{if(rev===revision.current)setBusy(false);}}
 async function apply(){if(!proposal)return;setBusy(true);setError('');try{await invoke('plan-apply',{proposalId:proposal.id,taskIds:accepted,placements:proposal.placements});setProposal(null);onPreview([]);setOpen(false);await features.load();onApplied();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function change(rows:Placement[],ids=accepted){if(!proposal)return;setProposal({...proposal,placements:rows});onPreview(rows.filter(p=>ids.includes(p.taskId)));}
 return <section className="card week-planner"><div className="card-head"><h2>Sugerir minha semana</h2><button disabled={busy} onClick={()=>{setOpen(!open);if(open){revision.current++;setProposal(null);onPreview([]);}}}>{open?'Fechar':'Escolher tarefas'}</button></div>{open&&<div className="settings-body"><p>A IA sugere uma ordem. Os horários respeitam duração, jornada e disponibilidade. Nada é reservado antes de aplicar.</p>{!proposal?<><div className="planner-selection">{eligible.map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} disabled={busy||selected.length>=20&&!selected.includes(t.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span>{t.title} · {t.minutes} min</span></label>)}</div>{!eligible.length&&<p>Nenhuma pendência disponível com estes filtros.</p>}<label>Orientação opcional<textarea maxLength={1000} value={instruction} disabled={busy} onChange={e=>setInstruction(e.target.value)} placeholder="Ex.: priorize as tarefas com prazo próximo"/></label><button className="primary" disabled={busy||!selected.length||!features.ai?.enabled||features.google?.connected&&!features.fresh} onClick={()=>void suggest()}>{busy?'Preparando proposta…':`Sugerir horários (${selected.length}/20)`}</button>{!features.ai?.enabled&&<p>Ative a IA nas configurações.</p>}{features.google?.connected&&!features.fresh&&<p>Atualize a agenda antes de sugerir horários.</p>}</>:<><p>Prévia · válida até {new Date(proposal.expires_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</p>{proposal.placements.map(p=>{const task=tasks.find(t=>t.id===p.taskId);return <div className="proposal-row" key={p.taskId}><label><input disabled={busy} type="checkbox" checked={accepted.includes(p.taskId)} onChange={e=>{const ids=e.target.checked?[...accepted,p.taskId]:accepted.filter(id=>id!==p.taskId);setAccepted(ids);onPreview(proposal.placements.filter(row=>ids.includes(row.taskId)));}}/>{task?.title}</label><input disabled={busy} type="datetime-local" step={900} aria-label={`Horário proposto para ${task?.title}`} value={localInput(p.start)} onChange={e=>{const at=new Date(e.target.value);if(!Number.isFinite(at.getTime()))return;change(proposal.placements.map(row=>row.taskId===p.taskId?{...row,start:at.toISOString(),end:new Date(at.getTime()+(task?.minutes??30)*60000).toISOString()}:row));}}/><small>{p.reason}</small></div>;})}{proposal.unplaced.length>0&&<p>Não couberam na semana: {proposal.unplaced.map(id=>tasks.find(t=>t.id===id)?.title).join(', ')}.</p>}<div className="toolbar"><button className="primary" disabled={busy||!accepted.length} onClick={()=>void apply()}>{busy?'Aplicando…':`Aplicar proposta (${accepted.length})`}</button><button disabled={busy} onClick={()=>{setProposal(null);onPreview([]);}}>Descartar / gerar outra</button></div></>}<p role="alert">{error}</p></div>}</section>;
}
